---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - persistentvolume.yaml
  - pvc.yaml
  - route.yaml
  - oidc-secret.sops.yaml
  - oidc-job.yaml
  - egress-allow-internet.yaml
  - ingress-allow-gateway.yaml

labels:
  - pairs:
      app.kubernetes.io/name: jellyfin
