apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-oidc
    namespace: jellyfin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:NB3MYn/eNztfui7R7S8DVtik57w/gSfL5xJi9//hGi3E7CdQ+psiBwcJd62JaJcLTDzSdZeGhSXa9aH9KE3sQD67vvazLV9EXhM3,iv:X/V03VBHO/hqRL8TRUHwoSvbvPsFp1WkCDp9lhfugcI=,tag:Ng0KA6YtCXDpV/RKTIxEhg==,type:comment]
    #ENC[AES256_GCM,data:HY/ss1xOP2hiPBnVImxVV6nrJ/lvg61SyVFi6anHU+DLCYHl5QdmJhZxMfmd6AHKy2IZNkZ7/2NAu9SnARbMGsI7x4M/TuiWVg==,iv:iJppd6oGGHa9qWZeuVVLJreRgtpHuTW0ZUNMJcJ/zmY=,tag:rqKzHFPIqWZhHnTusiWvMQ==,type:comment]
    JELLYFIN_ADMIN_USER: ENC[AES256_GCM,data:Ycuxvfc=,iv:SRonoeUowAw8MoXhM5idIhLg9XXKZ0iaLiXfmwyhVWU=,tag:ACER5+kSp60a7UCOtps2fQ==,type:str]
    JELLYFIN_ADMIN_PASSWORD: ENC[AES256_GCM,data:LbTkGoGbza75T84DgeEkyGERDX60IIXvSvxjlm0x79lcXD1Yym0rHjWE1ehOtUvf,iv:2btw5uWH4Gjfo5REG2DN3i/lL8aas9jG6Itx1r5dh4Y=,tag:p/MnGo8ogVhwVwC7gpYH8A==,type:str]
    #ENC[AES256_GCM,data:jeb0eSHXXlJxweAKzcdHNhT/PlmmDCNA3gU5XIRK5H5GGph57mpb2wKJ8xVm0meSm7YPNU3W+Ei/yMKgUdqPJa5clXj2bWRk,iv:fKcstUOeFMnhh2WAAyj7kB/JeUIWCkAwJqmARU070/E=,tag:DvvDhmISdcDcuKV15FJrPw==,type:comment]
    #ENC[AES256_GCM,data:Cq2fuZ0Za6Z9twODoPeMfcFfGdTmlkwn4ajughtAeawKvhzkyk7QaJjcgssIP7t00XyA4Nx+sa4giMlQU3RayQ==,iv:b8h1kbN0zO04s80BKQxA88WhjWBZqYLvDlaFdxBCYrU=,tag:2Zmy0eTWn7Pl3qBJBU3vEg==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:m2wLHYVArb/ClLx/YDRLpkKKtaWwlk7KXeEkbw1PMPzc36JNxNYvZifCh9SuCWC6knm/GGASxBZYoRMZmV7mDw==,iv:RQvtZajdKyonAwL6ReydRvLRdn3s1Tj9EH2cO0q1dBs=,tag:+c6cTcEkaa0BvKqlfVEk4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYnRDUHArblRSNWVjdytL
            eW5oQ3B3cTlmNWdnY0dpSHBnWXBKc21INlM4CllZVjZSbDhPVi9ZK3Z3Q1FRQ0RM
            VWxrVmRkeUY4UTYyMFFDTmJGSUVtWEUKLS0tIFcyUU9WSHpuVlRVRVk4eUJaVjFr
            SVhoV3pmSnRhSGJPc0Q1VEU2ZzVKUGcKpUXrRZni2BPGCnaPB0jKduiJHICSyLYi
            Dde7C3eq4gOvmIlWp0yWkOwjOefF3u7+I1LFfGd0MwLRvbKUrT8Dnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-20T08:00:32Z"
    mac: ENC[AES256_GCM,data:+gwI6JTBwa0k+GY272OWIjkZa5JWW/cwsx1mJRaIfp67Tqj33AWmApsJ9QgACWJefLrBylpQ8dCVoSh/wHJ4M5bZeYAk3my2P/e0lTWy+xATxWATt2H0qESSyMkYVTFr59uNqrf53/pyi9iyGJ+5ZiO9CwsMi28MNuzraNygYKA=,iv:IpanPggkVy/G53BBV4p+yiMYg+RtYh2FMYDz2rY8d1Y=,tag:03p0jQhfl9Qp0JrrgXk1zA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
