---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: media-jellyfin-library
  resources:
    requests:
      storage: 1Ti
