apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Y+Iy5NpXaFlmO1D8yokW+FoPzPDDzpSROY2JceMs6YSO9S2aYTKY6EwTK3tC4jhJJJxXKlY=,iv:yjy6cJiV9Wm5rZjhzVCwqTXELSAjm/8cYIh3IeJloic=,tag:PbGDEiWBVgck5mRro0mpFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN2krU3RxbjBnZGMyNU9o
            UGxCcGpmRE1lYjc1VGRVbEhJc2VFemF5NjNBCjJqSzE0elNiUk1pZFZ2Ym1pTmZ3
            SzJDTHBJYUc5UU1rTVBOem9OSzJZQlEKLS0tIERab2lOajU3WWpNL3BnMCs3UjJS
            T0RtOEV4dWhZc1BpM2p2ZVhZaTh2L2cKsMK2GPpzm/j3QqEqB67SLqAPYONy+FV/
            eI77Zt79RYkdF9I/CCiM60JSo1TUCSTpAZz+T0OdX7oQEKucoQwuKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-20T18:24:14Z"
    mac: ENC[AES256_GCM,data:JpQ7b3lXuxBZJeLGwlLFF994/3PosRfI36sqnVPtMU5xmj7EtHPuiao3EfapbsBEguXkAPxG9lB74/Tykb1No8l9vEPjW8GoQWhSTiktX6LK9U4Qzk0T204w90UFYndbBqpR4lWbSqwzMTXAae3CUYVQq14DHC/Asb3l/MQ2pIQ=,iv:/rnDzY2N9oOLZEy3peuL22VIqff5kLPqmz0poSZ7hE4=,tag:79n/LF0bkPSaExGb5FPh4w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
