---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - selfsigned-issuer.yaml
  - ca-certificate.yaml
  - ca-issuer.yaml
  - cloudflare-api-token.sops.yaml
  - letsencrypt-issuer.yaml
  - ocirepository.yaml
  - trust-manager-helmrelease.yaml
  - ca-bundle.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: cert-manager
