itemTemplates:
  - items:
      - name:  argocd
        chart:
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
          revision: 8.3.0
      - name:  argocd-objects
        chart:
          name: argocd-apps
          url: https://argoproj.github.io/argo-helm
          revision: 2.0.2
      - name:  cilium
        chart:
          name: cilium
          url: https://helm.cilium.io
          revision: 1.18.1
      - name: cloudflared
      - name: pocketid
    template: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: {{ .name }}
        namespace: argocd
      spec:
        project: default
        sources:
          {{ with .chart }}
          - chart: {{ .name }}
            repoURL: {{ .url }}
            targetRevision: {{ .revision }}
            helm:
              valueFiles:
                - $repository/manifests/{{ $.name }}/helm/values.yml
          {{ end }}
          - repoURL: https://github.com/tomerhanochi/homelab.git
            targetRevision: main
            path: manifests/{{ .name }}/vanilla
            ref: repository
        destination:
          server: in-cluster
        syncPolicy:
          automated:
            enabled: true
            prune: true
