---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 1h
  url: oci://quay.io/cilium/charts/cilium
  ref:
    tag: 1.19.6
    digest: sha256:b8d600c542c97dc8652429e12487ecce922d73de9785505457a8f653833e75f9
