apiVersion: v1
kind: Secret
metadata:
    name: hydra-database-credentials
    namespace: ory
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:sGigCnU=,iv:WRcncvlZaop/Izr1z5TvcPGo89amvb0uTuWZRMuQYUA=,tag:BQ2KvvCeWQ2P+cd98ETL4Q==,type:str]
    password: ENC[AES256_GCM,data:t9EdLm7PWWwYW4BneLb0X9fE+bzwx7M4l4usM/7MpQy3BinT7Y8utzrLx+0it34QMcia0Y+0sol+RgxP1I/+FId8Nr42+9u4ZUPybtPFOGi8NFMz22FrMLmUuUkKqpSQPqte1a+mKe99cFnuR2uqeL2qdHo8OXDHepG9dk6oF4U=,iv:HyW5XBKEjMmY5M3cz5O7qqJ/pJmdOKrMIzjelztquTA=,tag:A8O7DgdORLBrPJ+ubKWUjA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBJVnl1
            U3BUQ21Ncmcwd2kxM2pqVjVwTk1XNFpKNitWN3BITUFuQTl2cXdNCmdSNEVoejJB
            ZjZDd29HZDJWbVpqVTJiNWNIQ2hYTU95bXJkeDJCV2taY28KLS0tIFErNU5VY1V0
            WWZITTMza2pYemozMVpZZFJLTFoycVZlNHlmQnVSZ0RMREkK3vqEN0k5i6nTy06u
            DxS3Mcog7+s5hsK1eYVFR5C9PJaVXVHscZ3FJOTG/TD/M4qXPmz339DpRcz+dDxZ
            +/gymQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T21:18:14Z"
    mac: ENC[AES256_GCM,data:SFAOGu6JRip/1ptBaZyUDT2Czdmok5Nap/WtUYweW+lLhAg+FIFLh30vIa1mV4xD9p3Q2/U5Tk8U28vAEDvzdqu8z4mbWdfEAdbAduDDUOgPK2FE2cnwKHqoaJXr+RrjQd0+o6D6jnsiF7mStx8jdTYjjd1muUQipNBAi4kOoeg=,iv:3oe/B7y2jsPw+umMJ5yeggVNBflDfOobrqc/0RMqtAA=,tag:2SMhr0snpGvk+jEW0EhjZg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
