---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hydra-database-replication
  namespace: ory
spec:
  secretName: hydra-database-replication-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: streaming_replica
  usages:
    - digital signature
    - key encipherment
    - client auth
  duration: 2160h
  renewBefore: 360h
