apiVersion: v1
kind: Secret
metadata:
    name: hydra
    namespace: ory
stringData:
    dsn: ENC[AES256_GCM,data:qHB+cax6hAYGNqz0ZaKZjCzshP70U6WwEBJYWolBfubgLQ3dXXYdDRTrWJMCmWczYFK+BlhUfskh68dfTO6zxwp+3uNhbQr0r9Ewou7SdQ8fjGnz3VY/84LiDUz/m0xHSWm+2GbvYJyi/wttAgicSHMxWHirtFH7dScrnr197X6ARHLFdX7F5VxyOR65SLcK78bae6s37QS3Cdj70WFJaPo9LJNlU5inBMoQAQ0dC5hNSyGS1lGTeXba8PCmU7eTYdc=,iv:Qzpdcd8VyhyDd1SgFtBxjZSfXc6fC+JKc6z5l8xTcEc=,tag:6t7hAznVOwEcCt1xZ+XBZg==,type:str]
    secretsCookie: ENC[AES256_GCM,data:xSlztduMlQHSOg+GdVFpb2ZOUWXDhiH9qTJEyKRg+5aWOv9FsiCVUOEocaVZTWrwURQrFGeNIU4nDs4gvX7sxmSkCHb/iSVKZauXuxazWUaaTHjFVwu9xxRwvb8R4EBhiDPGTVfhv+UhglJpqyK9rtt9mHID4BniPF1MhTjmbng=,iv:DsMtsPYRB+hWJDbhjrZs5P1CEohE6fukucAISYh8df0=,tag:/9WlmiZ5vbR+1G7DtFNscA==,type:str]
    secretsSystem: ENC[AES256_GCM,data:O4O0b44nizGqrwY3LYCubIoOGeK7sMK8AAZXSQ6vhzDg+ufqEjtAyC3os08YTW2Y/wy962XMAJ1ohLxurMZ0ZC0U3plmg4KrpGFR5BnJQF77Aa4VdkSVsh+AR+LNGm5lBdYIWPNbvs07H8p/R+4WVCuqEClIbXNNBoGHywGwRvQ=,iv:u3EB1e3yAxRd9umTEsT9jEPLDZkmtAd6Vt67FZ9E2uw=,tag:/JUxv4CGoPJAk4jeVabZng==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBhTFVC
            d21xTlZaS3cyeUt5S3MxaGdabFNTSU1lOHZvN1Q2NlVDNkFIUnk4Cnd4Wjl0WXpC
            ZUgyT1AzRGp0WkgyU1ZUVFdaVUUycGs2ZlNYaURiQm0ycG8KLS0tIDgwMEZMa0ZN
            M3RhcC9qRisxWTAyR0NFeXVMUmdOOXdnbWNWaC9hdHRzRkkKosei4Ej9LjcI7mzD
            TdYMu7izVcG7xyDLDUxnIkNIU3TMdjwsI2iU1rrdwAQ+UnoLcBYAaa3w/6ki/1zt
            Jjc+Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T10:27:26Z"
    mac: ENC[AES256_GCM,data:kxb7ZS6N351OJbwqc2zWbgV7+fsNjDeCimQ4q6FsBDpIesuB2ycHeajZRZTSVXq5+Pm+9gpcRVmD/Dy52mTBv660t0F9LvUuVHM5THK9M8/4R7cFYwc+ymc+dKd3+SnSxoNCYPvah+FkMWyDa4JZ1mSAZWxbDw42S1FXl+Yulbc=,iv:hOB617srABsrmPMki3EH9NgJd1SeDrJQjUIJb3bWPrg=,tag:DKupEjcdol2xKSJqq3dfPA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
