apiVersion: v1
kind: Secret
metadata:
    name: hydra-secret
    namespace: ory
stringData:
    dsn: ENC[AES256_GCM,data:J2n1mHQTKQCBrUAHisHC48BUfsIkZ6pR39zz7oXsubAoA7f8fXYwBpuDRHtYbDcWnug2mRxeW9sSR0nKtqDCDI0Op6FaThoV8lu4w+sWS5+bSKpRRfWtW4IR9Xyxes6KFLgaNCrye7vNvfIYQQB9EEYtQbtcaJaI9dNkjwWuUQxjO5o2+UiHQvzO1fWT3TwqJ5gyicuGHsAN0rkvmfjdVLSXmuZliR++B61eXGp8R8ZyGlpO3ZCtW+hfMaWi/JQ0VurT9lL4gMRwTkUvQdBMEY/xbDE59PbI3ZUlTjxt240BVhBRkPZbuognWRYW2j4=,iv:85w7AGt8Qn7sLqImy4DiaFBFmBda60+vuxXbZhhp6vw=,tag:slzpj00MyZefQLgSS0jV9Q==,type:str]
    secretsCookie: ENC[AES256_GCM,data:xSlztduMlQHSOg+GdVFpb2ZOUWXDhiH9qTJEyKRg+5aWOv9FsiCVUOEocaVZTWrwURQrFGeNIU4nDs4gvX7sxmSkCHb/iSVKZauXuxazWUaaTHjFVwu9xxRwvb8R4EBhiDPGTVfhv+UhglJpqyK9rtt9mHID4BniPF1MhTjmbng=,iv:DsMtsPYRB+hWJDbhjrZs5P1CEohE6fukucAISYh8df0=,tag:/9WlmiZ5vbR+1G7DtFNscA==,type:str]
    secretsSystem: ENC[AES256_GCM,data:O4O0b44nizGqrwY3LYCubIoOGeK7sMK8AAZXSQ6vhzDg+ufqEjtAyC3os08YTW2Y/wy962XMAJ1ohLxurMZ0ZC0U3plmg4KrpGFR5BnJQF77Aa4VdkSVsh+AR+LNGm5lBdYIWPNbvs07H8p/R+4WVCuqEClIbXNNBoGHywGwRvQ=,iv:u3EB1e3yAxRd9umTEsT9jEPLDZkmtAd6Vt67FZ9E2uw=,tag:/JUxv4CGoPJAk4jeVabZng==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBhTFVC
            d21xTlZaS3cyeUt5S3MxaGdabFNTSU1lOHZvN1Q2NlVDNkFIUnk4Cnd4Wjl0WXpC
            ZUgyT1AzRGp0WkgyU1ZUVFdaVUUycGs2ZlNYaURiQm0ycG8KLS0tIDgwMEZMa0ZN
            M3RhcC9qRisxWTAyR0NFeXVMUmdOOXdnbWNWaC9hdHRzRkkKosei4Ej9LjcI7mzD
            TdYMu7izVcG7xyDLDUxnIkNIU3TMdjwsI2iU1rrdwAQ+UnoLcBYAaa3w/6ki/1zt
            Jjc+Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T09:20:45Z"
    mac: ENC[AES256_GCM,data:rbk2/yAbuBaQyF3+X8b5mdTM2sjejERbNqw3OAyNqij91C3a6cX4/kx6kFum6lBLwr1nW4udRyImF7JKaDtE0jJTb14Cuv+dtijDzV8GWZoaC7vSGOGJasCTflHsXU6I3qzbhU3RSqI/do+EbXJCzB7dvNcAlI5pxy5rWVlyb/o=,iv:pWVJgoJGiZ/CV3pXA2z2TcXQ5BZAqNnqovtcPHqC5VI=,tag:6MhH1bTxaR9LBlEU5kVthw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
