---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: hydra-secret-generator
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: ksops
files:
  - postgres-cluster-credentials.sops.yaml
  - secret.sops.yaml
