apiVersion: v1
kind: Secret
metadata:
    name: hydra-secret
    namespace: ory
stringData:
    dsn: ENC[AES256_GCM,data:s1ZaQBq3wSgf3EDn2xHNkuptvdHbvu6ncm67YkhVjHemZNEmkBF9Q/NVGTb6KpkePMCjXQrhORBIJdP/eRiAXF8fDQVe6mp8Bv6CY0qkJuERnuQeAW2sX1uLBmwkdqqYYWOSYzJQGqHCAUSKrs1S59lqV2hAlK3EaG36o6IWVxCtL8kgGoA23JvmZg69bJv4HV6O3rP11f8b9ZwqIWZsmXQx6FM7ezn0pRB+HuyP25stuyHvec3gQOwcNvha+wneVNgYqYP6p5j4jBvEdFFGtXZDu3+tiL8H3jeEW0q6pmUDiSVzSzAUjaZrIr967T2v,iv:WNFZTDzn1S/rA9uonLMYEbwbY6MYkYPcdNg86++toZs=,tag:d1kGsD6AvDQe4NXYJ933Dg==,type:str]
    secretsCookie: ENC[AES256_GCM,data:xSlztduMlQHSOg+GdVFpb2ZOUWXDhiH9qTJEyKRg+5aWOv9FsiCVUOEocaVZTWrwURQrFGeNIU4nDs4gvX7sxmSkCHb/iSVKZauXuxazWUaaTHjFVwu9xxRwvb8R4EBhiDPGTVfhv+UhglJpqyK9rtt9mHID4BniPF1MhTjmbng=,iv:DsMtsPYRB+hWJDbhjrZs5P1CEohE6fukucAISYh8df0=,tag:/9WlmiZ5vbR+1G7DtFNscA==,type:str]
    secretsSystem: ENC[AES256_GCM,data:O4O0b44nizGqrwY3LYCubIoOGeK7sMK8AAZXSQ6vhzDg+ufqEjtAyC3os08YTW2Y/wy962XMAJ1ohLxurMZ0ZC0U3plmg4KrpGFR5BnJQF77Aa4VdkSVsh+AR+LNGm5lBdYIWPNbvs07H8p/R+4WVCuqEClIbXNNBoGHywGwRvQ=,iv:u3EB1e3yAxRd9umTEsT9jEPLDZkmtAd6Vt67FZ9E2uw=,tag:/JUxv4CGoPJAk4jeVabZng==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBhTFVC
            d21xTlZaS3cyeUt5S3MxaGdabFNTSU1lOHZvN1Q2NlVDNkFIUnk4Cnd4Wjl0WXpC
            ZUgyT1AzRGp0WkgyU1ZUVFdaVUUycGs2ZlNYaURiQm0ycG8KLS0tIDgwMEZMa0ZN
            M3RhcC9qRisxWTAyR0NFeXVMUmdOOXdnbWNWaC9hdHRzRkkKosei4Ej9LjcI7mzD
            TdYMu7izVcG7xyDLDUxnIkNIU3TMdjwsI2iU1rrdwAQ+UnoLcBYAaa3w/6ki/1zt
            Jjc+Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T09:13:23Z"
    mac: ENC[AES256_GCM,data:ZTAsdB1GJnUnSFDLWJxyY2L7CBl2Czu6MU6LTcQN0g/GTTxhuwIvQ6l8oKnMdG+8Fsvj601x+oB3jMp8DL+J+bG+H6IXf6WG+uAVjz5qEQiH+eKQ1FcCDyMQEP6d4yURgAhIa+2nEcRRB+xd65zjuFkKtA2Y0s35lkuFOT+I42M=,iv:nUIHBpmDPTWlTC6Tn3uXP7EGqpGueptDvJFUCv3oEk8=,tag:YCEY4guTnqhIHquKuBc0Yw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
