---
hydra:
  automigration:
    enabled: true
    type: initContainer
  config:
    serve:
      public:
        port: 4444
      admin:
        port: 4445
    urls:
      self:
        issuer: https://auth.tomerhanochi.com
      login: https://accounts.tomerhanochi.com/login
      consent: https://accounts.tomerhanochi.com/consent
      logout: https://accounts.tomerhanochi.com/logout
      error: https://accounts.tomerhanochi.com/error
    oauth2:
      expose_internal_errors: false
    log:
      format: json
      level: warn
    ttl:
      access_token: 1h
      refresh_token: 720h
      id_token: 1h
      auth_code: 10m
      login_consent_request: 30m

secret:
  enabled: false
  nameOverride: hydra

deployment:
  initContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  extraVolumes:
    - name: ca-bundle
      configMap:
        name: ca-bundle
  extraVolumeMounts:
    - name: ca-bundle
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: ca-certificates.crt
      readOnly: true

service:
  public:
    type: ClusterIP
  admin:
    type: ClusterIP

maester:
  enabled: true

hydra-maester:
  adminService:
    port: 4445
