apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:AeEVW7UBY/8=,iv:Ho00rINi7ReMOVBjjsGyaSxd9OmnwYnVxqTG7hHC1gk=,tag:G4MXBlVIPrBWVMRNjwKbYw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/93wL6tguApziBUUIY10QQsQFNmJpetfak/P2N9PFVa6k7G55K9CGpIG90hhsjOOBzxGD0mNGbtoCWC/CaTDZw==,iv:EdgboAsyMopRnycFgnb+fzdaEYCJndyP5DDfK3XoQi8=,tag:qqAmCEwP7B+9qAk3JQRnww==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:/2MU+np7laHjzH8Rjw3t26POFCG275sQ++nftJwVaJs3lvCJw8haQuTkXNAQ83Uge6Ap3w==,iv:J919nmNw6Ytn3FDOyKDg57KYOPZtpTEVF6INNK6C49w=,tag:CR4tuuIO5YZ2a7kHF/b5PQ==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:XHpaADJKh5deWHHaeZoVIaWJl1cYf8m1bwl45dsKdVEGJcLFtquLPbnf,iv:qGSzlnjkY/sgk7Uo+Jfp5urXLsBKqkFOmJp9K9JAdUA=,tag:fkvtF4W5GWEzMNckjtJ7zQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWmlYcjVhYjQvVTJ6YlNO
            QkVsN0V0VHBZU2NJQzlhTkxodks0VkM1Mm5JCm9OcXRhQjdia1RkcTJJUDFEZkNQ
            OEREZTkwY2xxNEVjSXprM0p3SlM5T2sKLS0tIEwxOHd5alRaVEswek05RFMxbUN2
            SXlFZ1RCQnl3cEdzTmN0VTB2WU1qaFEKKzMuUvpThy9MJ/z4DKbmNgBPf0Xy0HVw
            0Q1Y1QGscyJBF1/wTsz2SJyePGzbh8M1l5zz+zag0XdeRiHfGltCZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T20:38:54Z"
    mac: ENC[AES256_GCM,data:aDfuIoa/zA4GAKuQS89bWIssBm7LQl6GicBLexV+TSMH7EOPbGS0kJOi8TVVHPwhT9NYaS6XwgaY1AU/Cp3Z/zR/AuMx/UdS5stwic6PsY4PGrkKApQtSMUqE3CepzoaWIT/yEmVTh8yfah0wZoASTpiEwHaLunQkhFoYPD3usE=,iv:y63UcmNTflinN2JHKa6IHZIIKW5ktiKW7e1uSDNhzmg=,tag:Z/qn60ldv02MyJkhvsWyHw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
