---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml
  - networkpolicies

helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    version: 2.7.0
    releaseName: jellyfin
    namespace: jellyfin
    valuesFile: values.yaml

patches:
  - target:
      kind: CustomResourceDefinition
    path: patches/crd-argocd-sync-options.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: jellyfin
