---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: media-jellyfin-library
  resources:
    requests:
      storage: 1Ti
