---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    inject-ca-bundle: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
