---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ca-bundle.yaml

helmCharts:
  - name: trust-manager
    repo: oci://quay.io/jetstack/charts
    version: v0.22.0
    releaseName: trust-manager
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
