---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cloudflare-api-token.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - networkpolicies

labels:
  - pairs:
      app.kubernetes.io/part-of: trust-manager
