---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pocketid-database
  namespace: pocketid
spec:
  instances: 1
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: pocketid
      owner: pocketid
      secret:
        name: pocketid-database-credentials
