apiVersion: v1
kind: Secret
metadata:
    name: pocketid-database-credentials
    namespace: pocketid
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LJguAIRuQUU=,iv:/75cLHS+YhoQUOHiVCYvESuIPASZNHaJ2j88ZJKid7I=,tag:qWC4FTjxuoQ/rOTM4ag4fA==,type:str]
    password: ENC[AES256_GCM,data:2/o137QF+seYe3V6qxiiKU9ykHeYsTaHG+qrRfmOA2pQq12eapqbmxIbtqhifusf,iv:pKCtnOSaLZ7dNhemqoHR54uvLJo5R10IYj6AY6PdLdo=,tag:hcjK5iKAZcSKKl69GwTIuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVytINXlHbzl3MUlUMlZD
            WHlDQUNaOWl2ZDlrMnVqU3BhTkhtREFKbGpZCjlNZzc3MXFTa0lXNzZUS1pMdzhs
            RFpiTlpGQThJNWxmREp2a25hZW1XeUkKLS0tIEkwSUhZOTJJeEdqVjEvcUJkY2Vu
            eXYzL0ZKWTRSaVRkVDJLdHlHdE9EcGcKURQGLu5ssn+Ho2+Zzq15R17rh0FsbnG3
            jwERCWVQWGDU2LvqzyMXPZfo2NWd9SP1Xg3+n7gl3/r/U6Rg4XR6mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:07:40Z"
    mac: ENC[AES256_GCM,data:Nadkkz13DVA5NWgnyfQE2vpehWwSjppJnvpyQ5ybz3CdZ2hQvF5oV1vciRzc9Kcyj04GL2vmG0z4WiJxbaJG2N3TuH6Q45gOEtghJawvl6vvl/aovC5Vxgrk1Bn6+N01hfe/32OSMKvJuBWU1T8zAoozcbH/xgufRn7kmlBdEfM=,iv:U2FPwsv+wEWnSQyhymKkJNYCfnMirnSAWWemY3q8BII=,tag:to9ucryt7P/Zfp+/glYOkQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
