apiVersion: v1
kind: Secret
metadata:
    name: pocketid-secrets
    namespace: pocketid
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:JGOdC6wmc1Oi7+RC6euO5ZTJJbLzJHsrW4liH52uOKl1cbDw//IT8y6XB8Q=,iv:hVTSNhjIDlFdW8VnZvp7yLrXHSG5XWR+9QmyxojgKQk=,tag:4DmlgNLinLniy1VviIx0iw==,type:str]
    STATIC_API_KEY: ENC[AES256_GCM,data:y4XsWlL0vfVP8uHlEZLhTlwHeZ16ApxUMuG9CKRkuCpocJefaxI64OPUaH+JwiK6,iv:OyzwNzuhYw1s7p19QdkwQjS51BpXlGmAkVO0rrwSDdM=,tag:jImtZT2fbUHseXC6ZmEs8w==,type:str]
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:yssYcF3q73YODgsLI6IRQ1E8mUecCz8yXVaY4aXbGyhZe/TjMWJnQcKcPvvP6cACgXDzYwojxF3P7GlOdnxdvAb1P9VD0HOP5Pm1mCArp4AqAwBWgNYgrXfMtgCj3QxXs/QfqyfXYjai5NFAIiq17wRd0Z/CoAKNkVcOxpAzSdPCi6St,iv:ycxkR/Q3DV9wkq0LAYV9RGobUWo/Q/cIfkxAWDj5Djc=,tag:0FzheS3apeviynUOeIIqsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRDNTOVNmM2F6ejh2Qzl6
            djdQUW03OWVQY1BNdzVSOXZ5ZHl0U3lYdzJNCm53YnhZVElxSDZ5TzFmV25yT3NZ
            WkcwYWNLZDlZeHNBYXRiMXYwZG5UY0kKLS0tIFBDNTRubEEvUGlickxlMkJjaG8z
            Z1AyeDcvRytVajVnSTdhRzR5aWJOT1UKB6tAUrG0Bo9q9fosUaaZdkgLij59cTNU
            lbSQ9R6JR6Gh6TE7ol1lCI3MZJH7hmd85C2f7bP1ZQHtGnkJRj6IYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:07:40Z"
    mac: ENC[AES256_GCM,data:10j7Y4ibvII7wtHlI0MmAUAKjLp1185COBmREG5ReUcKRFshXQ5N2TT6gJ9h/9gJd16h7HTKjKpYMkaqWdSJ1wGG3GII659Nsw+8v5i9XZdWEr05KAYAXvUCxSP4hq0mPfg2H0c65OooFFmJItcSmnZ/c4Ptd5bIoTs2v3hCkNc=,iv:6ifsLe7O74gAd8V7zGRPiZURq774VDFGOCS5DvkH+X0=,tag:d8IgBUV5j1HZ1uxDpxJvbw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
