---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  argocd.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: argocd-oidc
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: ArgoCD Provider
        attrs:
          client_id: argocd
          client_secret: !File /run/secrets/argocd/client_secret
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          redirect_uris: |
            https://argocd.glb.svc.tomerhanochi.com/api/dex/callback
            https://argocd.int.svc.tomerhanochi.com/api/dex/callback
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, groups]]
      - model: authentik_core.application
        identifiers:
          slug: argocd
        attrs:
          name: ArgoCD
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, "ArgoCD Provider"]]
          group: "Infrastructure"
  jellyfin.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: jellyfin-oidc
    entries:
      - model: authentik_core.group
        identifiers:
          name: Jellyfin Users
        attrs:
          is_superuser: false
      - model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: Jellyfin Provider
        attrs:
          client_id: jellyfin
          client_secret: !File /run/secrets/jellyfin/client_secret
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          redirect_uris: |
            https://jellyfin.glb.svc.tomerhanochi.com/sso/OID/redirect/authentik
            https://jellyfin.int.svc.tomerhanochi.com/sso/OID/redirect/authentik
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, groups]]
      - model: authentik_core.application
        identifiers:
          slug: jellyfin
        attrs:
          name: Jellyfin
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, "Jellyfin Provider"]]
          group: "Media"
