---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - blueprints.yaml
  - secret-generator.yaml

helmCharts:
  - name: authentik
    repo: https://goauthentik.github.io/helm
    version: 2026.2.0
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: authentik
