apiVersion: v1
kind: Secret
metadata:
    name: authentik-oidc
    namespace: authentik
type: Opaque
stringData:
    FORGEJO_CLIENT_SECRET: ENC[AES256_GCM,data:75hkRChi9/AdI0rhlMeKkREZpaUEK4JSStWQDtV/vJKEeDSlAMB9B/3S1X//s21yoyZM790UGSsSer3MZjvMTQ==,iv:gn8Y46auJcKQ2+kM+6I+T3TpQnFwaoDH33UFxunmKoo=,tag:4Q/YnuMpVfW92Hp5TnwxaQ==,type:str]
    HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:I1zMpZoRyKbXkwxCdYg2SLZlZPdPUUPcVXRBWqGHIFEmDRHgSWBoFWUwi4bGn9W6xQWKFbXnM7UhpE2ufuor3A==,iv:sgWmHuMFut+p3UrD/WEhe8JcrNMZR27ed9+wPOibgYM=,tag:4iiZ5deESYB6p0xpCb/QoA==,type:str]
    KUBERNETES_CLIENT_SECRET: ENC[AES256_GCM,data:XWnEytKHypXJv6GSIaBz9ytyNgPuiyVQdr1RxrZp+/19JWvwhqy9rl6esFCu1b2nOL/Q4cXgPyE7c8jQJG2FTA==,iv:w5DAwK6Y2FHdQ5p2yarHOSOC7PENln2K4VjrjLyG868=,tag:7hPO7eHvXJFL5FGnxmUvQg==,type:str]
    JELLYFIN_CLIENT_SECRET: ENC[AES256_GCM,data:x+HArW2EVHaAfRpcnRCJQxxS8hHOPoBx6A5x0AY35AojmuXkxbHTT/u6eyUJPRI9NZOiqNQR3mWZkC9in3XsrA==,iv:8fIjaCuYfPHW1bbl8QudC4QJrnlpmwglamxvKd1l23I=,tag:8PFtuuhSUnaXLpkyInBZPg==,type:str]
    KAVITA_CLIENT_SECRET: ENC[AES256_GCM,data:xdsMi9CyzGlqkaRyAFfZCbr1XRxXcvFQJP0ytHbX6Mf1J7QpxqYl+BD8SrA6CCpJ81mq8uSRA+nu1eHN17aLWQ==,iv:3C7Orq5setDEXouioc2KD+G/XQFi48sb1eQF9kIcS+g=,tag:pn5qMxDs9dhgtAjDWkovKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdml4blZVSytTZURKTXEx
            ZzQwOHpFdzNDOUhaN2hMRW9pYmNNaTdMMmh3CkZjK1NvRWVEMURNT3RWZjg4bkp2
            bUVnSDN3UU9iNjdIZzgxTmRQZ1JnbmcKLS0tIDliK2VpSmdhbEJmS3BaQ3g3S2Fl
            cDdrbkt5bGJFbmRMRjBPUk5QU0RhRzQKvBnWtmia1Q2Bb2DHvNKHc+AgFORSgPr+
            At8TWQo0z4k0kXmDiJWqxu0nbWmRZzdycwfFF47ktwuTqsyDV78wUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-23T20:35:08Z"
    mac: ENC[AES256_GCM,data:sy/moYUZ/qXUoXLXzDgsWdkY8Go2sHbBDIEocMWbn7kA4R14dj6R/+bpjHTNcBaEA25zQfspM/Z38tgKkV7G+MeGgee3WawGKAMUzaQmVC6U2oxu69KSgOMRHxhSVNatf4nkABTOr8ON0HrPwBtf2eogX26f3f3buxBcvGi8tVA=,iv:xJIcpMLZ89BUdCtgnWFEjwU4DIx4k2HenzGVEmMeFdg=,tag:PDOrb+DM8Ga+PZ8ImtYVyA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
