apiVersion: v1
kind: Secret
metadata:
    name: authentik-oidc
    namespace: authentik
type: Opaque
stringData:
    FORGEJO_CLIENT_SECRET: ENC[AES256_GCM,data:75hkRChi9/AdI0rhlMeKkREZpaUEK4JSStWQDtV/vJKEeDSlAMB9B/3S1X//s21yoyZM790UGSsSer3MZjvMTQ==,iv:gn8Y46auJcKQ2+kM+6I+T3TpQnFwaoDH33UFxunmKoo=,tag:4Q/YnuMpVfW92Hp5TnwxaQ==,type:str]
    PAPERLESS_CLIENT_SECRET: ENC[AES256_GCM,data:aXAk378yPL9xOHB4d4DhFSdoJzFZhdu66BD3DHWXG0kJveEG3uxHhq/Gu2BDrV9EsN3jwF605d6H57N7Tz31xQ==,iv:yVsALND1XkeAKScUYTSNJ0pYI7FGtYBJ0kczw/1wXAw=,tag:zfKvgwmZWYcz0RigZQkJog==,type:str]
    HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:I1zMpZoRyKbXkwxCdYg2SLZlZPdPUUPcVXRBWqGHIFEmDRHgSWBoFWUwi4bGn9W6xQWKFbXnM7UhpE2ufuor3A==,iv:sgWmHuMFut+p3UrD/WEhe8JcrNMZR27ed9+wPOibgYM=,tag:4iiZ5deESYB6p0xpCb/QoA==,type:str]
    KUBERNETES_CLIENT_SECRET: ENC[AES256_GCM,data:XWnEytKHypXJv6GSIaBz9ytyNgPuiyVQdr1RxrZp+/19JWvwhqy9rl6esFCu1b2nOL/Q4cXgPyE7c8jQJG2FTA==,iv:w5DAwK6Y2FHdQ5p2yarHOSOC7PENln2K4VjrjLyG868=,tag:7hPO7eHvXJFL5FGnxmUvQg==,type:str]
    JELLYFIN_CLIENT_SECRET: ENC[AES256_GCM,data:QtD+nfP4zb6hF8eDDBKH2VTkkxyFyNDTv8D8S2bh65JsChySF4ZstrbDldQinxU0hypOJe31xZj7TZHIqMKNzQ==,iv:5DWKQkddfim48+yKwHYyJsWoVN+svDF8gZtVsBZBMuc=,tag:HD1P20oZ5ioMFxkViqepWQ==,type:str]
    KAVITA_CLIENT_SECRET: ENC[AES256_GCM,data:feM9Tzz/+8MbeyCyT6UI0kKR5iyPURrWz2sI/c5QQNQ8qbPzSSA369YB0kVdvtIc9prNds1+kMTBlL/tev2edA==,iv:gHY4yimHqVetm/b+YsPHBpB4YIaJr8ai4QIlyQ1wxGs=,tag:cOa19Z94js+qYpytQgpa/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdml4blZVSytTZURKTXEx
            ZzQwOHpFdzNDOUhaN2hMRW9pYmNNaTdMMmh3CkZjK1NvRWVEMURNT3RWZjg4bkp2
            bUVnSDN3UU9iNjdIZzgxTmRQZ1JnbmcKLS0tIDliK2VpSmdhbEJmS3BaQ3g3S2Fl
            cDdrbkt5bGJFbmRMRjBPUk5QU0RhRzQKvBnWtmia1Q2Bb2DHvNKHc+AgFORSgPr+
            At8TWQo0z4k0kXmDiJWqxu0nbWmRZzdycwfFF47ktwuTqsyDV78wUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T20:36:19Z"
    mac: ENC[AES256_GCM,data:b3mKWzB4tx+aejWJbnZxzpDo40MsniFdyAiFiU2XJxXfmrUnMYlq8VUQZR+XH7tu3l/6PrQ0YF2m4/6+OFCil4yX7zZRBvbyo61hTu52liTXvf0IufxrnGT714FI7urV6R+SNu4WD7hhQEuyD6lY1l7KYOKL5Lx/5MF4hjHzTL0=,iv:+mhP26TfcnOXr/MPFBocBIcXr8J8kV8D5ZkLz74g+/c=,tag:3y3zIpsvQaBWAqIJoljxSA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
