apiVersion: v1
kind: Secret
metadata:
    name: authentik-database-credentials
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:f/kFCkTzDw9j,iv:qDgep5wBjYRfVIbD0hBIW5+Fzqna28RMSgVJ7XAxOxg=,tag:eshWP/+EAOZy+91zHm4fyg==,type:str]
    password: ENC[AES256_GCM,data:VpkYPW42qwlsxCd2x3fPZ8kd78rEG47FvWR2485OBDNJnB/rixX22eMpzVaPKfET,iv:WqzshiQIFuOv3DvGPBFE3/xSEisOo7P269NriYzcNFE=,tag:aIWFLEmZnLRMmcUgluqh7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnVIUTNlY2pKZUZTamlR
            Tmh1elRjYWlOL2R5a05BL3JHdHpRRVFxRW5ZCktxRktUL1RUSEV2NEpjdWZUWG1i
            eS8ya0k0MTI2eHNIY3hvT2haQ2x0ekEKLS0tIHUwTkc4UmpNdnNjMEd3c1c5MUox
            OU8zcVpGUVlTMUNSUFlnMC9QNVdTRVEK00yAGjV8gmIFyEdb9o0W4sr+Q7fo7hGc
            6F/USXICPqqhC/3gksVKhxcks+iN5S4IQaue1xdEx9bNeihPjCYKBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T20:36:19Z"
    mac: ENC[AES256_GCM,data:5E3LLj8EGtB7jwRpH+xi1hgvUKdzNxDRoMRz94z2gYkODzFRP6brejVK8rlZF4n9F/QSBrIclRr06H1A0hGs617cDoD6Jts1wjuW2UDwpnsFjt+88q5jpuLcK4qh9NwxD96Ab0+DK2K1RPD4bWtL4W0E1h/6jHMKAhCN7r+sz5I=,iv:YerLEnsUkUTpFDHUTj8HQ6DlletZZrA35nB9cRe53U4=,tag:LAQe8LJx0HZxx+uffCnlzw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
