apiVersion: v1
kind: Secret
metadata:
    name: authentik-database-credentials
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ufsACpqbIMhh,iv:oXwRXf+medZvKOSUha42GnDtuo0r7l3SsEi/qfjVjbo=,tag:7Fm5YUGyB9PvGiGuZ0LMdw==,type:str]
    password: ENC[AES256_GCM,data:NFamgdf37svUOgKCky5j8dXqtjZph2K5JPPJJNcemp+SmfT1v7dEt2BW83dTGgsRpYrhfRmgSm16rX14SAgNIg==,iv:fsC2ieUH+eSfza2Rxoj+NLC05qoBt7x7AhlGDuOqDqs=,tag:UA4C8GZ1XekUoU3Y+LJ93A==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyAzY2ts
            UGp0N25NUko5UFQ1ZmZuSmpOOGFOa25qSVhrN3V4ZFBBWGtPTEdNCk9XT0FtTU1u
            Szd1b1pDL2sva3JvWGU0c1pZalU4VmlWekJuYjBEWHkwa0EKLS0tIHd0NEtFa1c5
            SXE5eWwvczFGM3dVdHBEUitnTFJJdU8wR2kvNFE0bHFVZ1kKMpL7A6tNliz+5OaM
            hOMdnrrNU0Tzko/pk/ghAjXt5gG3bOjYDBsAO/6eUVU0cwwbgx44a/MFS7GfK09V
            GxDxiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:24:08Z"
    mac: ENC[AES256_GCM,data:U/dOXhF14r7J0vdtAcXpuT8R+bJ8Y5rVeiG1hghpMbNGp1UI6XFQOwG88BXSkQLRzUXx21kXVpML80GCgNWZjG+x0l6eyTYM9MabRvTkPzBc4prX5xNB56bjmzAlnzqIZBm8Er4+nrIBvROAY0c4tarIJXjoVDCWti44kZcJGys=,iv:JttEyOuc2e4eGDjuhoMewy2KvDdOGz8I6IEQOaZye0c=,tag:hhaOu1JfjciChGFrUNBjPA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
