apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:ahb43oz/mIZDMB2vxQYq0SOr78ZfZv1Qwom7NGNUA4p1PckcIJDn6dIiDMv7If80JZvvXinGnfjZ0XS4ETkn+UCLTfUrdZbftE2I0NVvnfo=,iv:m5eosos9X4ZMW5/ldKQa0I6B4VhrbVkt/IwilZCYFHo=,tag:w7SXV9+GNf/MIQO3dWtK+w==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyA1YWlK
            eEMvV3FrSmZYUkxub2JMWlJtNUNTUElxV3RsbXhHemd4WjhhYWpVClF5dlB2Ry8x
            bEhsb2U0Q2pER1pVeFFFMXl0eFpBOVIrUlIrYTM4N0kyNkkKLS0tIFkwcXgyeGZY
            bWxxSEJVbUZ0V3hNMHZDZmJ0ak92WlY2S1lyLy9wOERBSWsKZHQO4oJTZxTtCDp/
            FaoREm+75ba75hNmeKiCxhOm2gLBI/LFT8keOKCNGorxbH7josvRT9OerUu8+4/x
            r1/kPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:24:39Z"
    mac: ENC[AES256_GCM,data:zFG7HT0Trrkh+LN19lu6EIDD/cqsXK6hQtHtUQ9f5TJHa0ilkcvJkVdmFS9XRs9HIJLkJX44tIzRCGZkHgtD1s9D+rxax1pU8FB7kOkWCZCr3IeVU/O4qObqq4WScTHD+4ZWXO7cg9FCCrcbryFCAa20iWEqIalOQxtLxwQMl0I=,iv:lzb4oA/5mkt0KT7UKNzvxRmod7/DG75Qr46Hw4BMHL8=,tag:mShtcTAFyFR1JS7paU+c7g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
