apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ruWSXoJ+HDQotHg49jOzRnJdh2JSSlJLEH3XaOtLpZdXIkg9jbC4QqQe3R6bE9XRExaWrpVHyM8E3Rc+,iv:dkcC/t2ZcyE6QdUf2WEr9lYnLaWMPQytTkR44c0MMhc=,tag:TtqcyGJT8UMqlKoMQtvOvw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:MoDw2t0pEuaCpUQrUVB0Tf4rV9u/VZ1OccLQ17kyBFU=,iv:eGcTHRMmi3K8WxILxPfg/IDajwxm3+tKt+MlEuRsLLE=,tag:G9JWziCgjVZm1lIleL0UJg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:99kYWrf/K1I+Fb7CoabxmwLYKK4q1XypShP2OPksWUDXJ+RB4YyyMwv6dWRTH+4vZYrqVlrtrmfWDQ6w5zaQtA==,iv:wodHI3Lz+CZYhMTxTQgkQqjd7EI+CzP3ku+EboNlQ6E=,tag:8EwB0GqzY3ugl2LtX2bjLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZzY4R3RQY0tVRys4TnRY
            ZHFIbExMV2ZDaE0zT2pSUG9NNzRSTmRQYTJFClNPcDh4Z0EzeC9sYjRKUVQ0Q1JQ
            Uk5jQlFIQ1BJT09SYlBpbUNWd1RUbHcKLS0tIHNWaHBZSHIyUVA0RDMzbTB4QXFh
            enhOb1Q2ek1WVkVIeXZZeklXQkpZOEkKHTzb6Xv+BkUMDBSfLHWsF1GQ4uY8iwR2
            CUlqNcqvJ0wKTfeQtEcpnJMT6MR8XQivCSsz8ZV5zSFRRSOzKSHwMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T20:36:19Z"
    mac: ENC[AES256_GCM,data:CnSoyLRg5n+C9Rre3gHNVwhW7lfUDpitrXKS6xWuli5NXfMSD5TPN+Qed8pHRUta+1citXD3pCc/OfK88W9lY5C+59zKmGW+zmtVELX8Ivnaygbgh4gDXwEXS48Z3+FvBUq66u1hEmKhle0jABLU41p5bH0oR4+kZykIWbs+uy8=,iv:KaVlsx4bvujs6FOds5WZ2+C0YeNPeSBwWwhT4nJBTMA=,tag:780Mhs0aL1JmN1XkAIERyw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
