apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:kOQjqbk0CkoJ8oWrvHV7MZg=,iv:NtONJ+Yh/RdCCdKIrVO+rGkXq7RCSYJwqOQySkfBhFY=,tag:6zdDTWph2K3VLhcgQI6TZA==,type:str]
    client_secret: ENC[AES256_GCM,data:rmVnGcYcmYi+zMyc9/+EhRiRKBNkk1l+q31mNgmv1CSB/+ejLBVehdTnbVfBLS77S2S7z7gNZ499KiogFz43,iv:Tv/Z+St+1Embgw3ef8NVqIvZmH7vUAkM/4l1p3nRlNs=,tag:PTneD6dpABL8/yh8w4IcZg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyA1Q3Jj
            VXZvbXdFQ0trTmo0Vjc5MlFsMTZSb0tKV1cyMDBubmU5TkVvbXhRCmNPNXVqQzNO
            ajJ4OGYweEdoSG40c2JEbk8ydUtTNVBNOENRRVBHMzdJZkEKLS0tIGdyOHlYSDJR
            VE1GekF4eTFKd3VBUmR5eGI1Q0hEZnd1UmcxR3dyZkR2SlUKfDgbeboxVDkwi/Lw
            wka4ximxSeOybryd/GP5mDQQP8ip3VZ49aQdyw09OyCTNeKG32TcMn7qbDfGpTWk
            j+Sr8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:23:43Z"
    mac: ENC[AES256_GCM,data:C1WqfomjEqmQ0dx1xzeWYSDhM99nq3wTx+eGZT7adU7gR9SOUSnSuzeK6yblRf2b4whylE6WszFF0B1oZKfC5IndMUS4kCQJnLyV7bihVIHdJ4DZEtDnLRmx7Wm/UItUwFeX9ZFTaao+6RZEotYmefRRjk0U0xDBDAyAB+aq/Vs=,iv:ma3HfyE6OGvj2WnKMzlQrw+n0nv4Kp9ajaYmvt2uPm4=,tag:EUFah5qt5Jv4cdElrjbsLA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
