---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-cluster.yaml
  - server-certificate.yaml
  - replication-certificate.yaml

generators:
  - secret-generator.yaml

helmCharts:
  - name: kratos
    repo: https://k8s.ory.sh/helm/charts
    version: 0.60.1
    releaseName: kratos
    namespace: ory
    valuesFile: values.yaml
    includeCRDs: true
