---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kratos-database
  namespace: ory
spec:
  instances: 1
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: kratos
      owner: kratos
      secret:
        name: kratos-database-credentials
  certificates:
    serverCASecret: kratos-database-server-tls
    serverTLSSecret: kratos-database-server-tls
    clientCASecret: kratos-database-server-tls
    replicationTLSSecret: kratos-database-replication-tls
