apiVersion: v1
kind: Secret
metadata:
    name: kratos-database-credentials
    namespace: ory
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:yZYEPTFL,iv:GkLQP+w3v0SfJYiQ+5EksxiiKsc4MnVPMh/cNs60bFM=,tag:yRq/wf8/FZXbDAuk5qFSQg==,type:str]
    password: ENC[AES256_GCM,data:0ceVQFxNp41TQHROUHM1Id1gYJHBHJ09dcQMMJrPBQthR1/B/kfDkL77VQ5abjMvWSO2igVdVvnneMdTEKlPnUj0Ck3s9TljZVnWQBTdYP2cSI3d8Nj0uHeDWOlcfSwCELZp4OcsBbJVZRmFLY9erpExv1VlHIeNAi+6a6UulhE=,iv:x/H0nVnWqiKSApweNGKX5usJebO0GYJYn2aGd6QGWsA=,tag:EZ5+/9f0Pb5/hoXvHOU4Bw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBvVDcz
            YTE1UXVQR09jN3ZrWjJEc1NlWGZHMnlzdHZOazVHR3c4QUlReHhjCmducnhBMHhI
            bHpjMW0va3dGVVFGUG1aSThsUUQrTTBldFV4K0R3YytIYWMKLS0tIEwzVnlQWUdr
            dTd6TzBHWlVuTnU5RE1aNWNOR0N4cTRMVXA3WUdoQ0RjQUkKDOe+ISWgoLnvtlO2
            mzSUztl5e9/ycdenigFl3tA170kNe2HkNJ/3kc3Tp8aTMoikiUrR1eP3PZpH65+t
            S+bFtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T21:18:50Z"
    mac: ENC[AES256_GCM,data:V9Gm1QSestMM7YucQpASl3+T/sqfoicQcokAQKRrvVil8ktmmfyKCzf7VgwQF0J6AAmqQncPyJbWyfNcp4brFlJjDL/fCjJyWzakva23Ki8KT2Q6LoJqsqcNsmRqC8VQMbrJnlCssKkW/naOjfqSNwtpb5xHWj0rVv6ujqRsuVA=,iv:VBo3pW1Ljiox0EjHFYfa9X0/1fozC/PoQXaGGo4clyY=,tag:4MQAJFr6JTBA/0hEGFGQIw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
