apiVersion: v1
kind: Secret
metadata:
    name: kratos-secret
    namespace: ory
stringData:
    secretsCipher: ENC[AES256_GCM,data:vdKhoP8dUm8AQkVFpsB2EqITr+ibp8MItDvUFNF+eOZovRNkIakmUpGe/P+tT590ojFjYr/cFcJa81/EU/IOjOAQOMIWXAMuo5bvLD3OerjXgHz8Yab8eWqapKPfYo7qy2g95Z2yltis0WBz4CcDj3FtNfN0npKPKP6t8kAzi9k=,iv:w6/b0FULJcgY6Vz4xYSGRvJrduIWJNbdNqlTvSh/xQU=,tag:QzqRhPDf5lUP/uAiBur4aQ==,type:str]
    secretsCookie: ENC[AES256_GCM,data:CP/CXtuKMQoU2w9YBTCg0ouil0JycO7VYo0p9sUOBMGmj3jSlpDxWcL/mNmF6eHcQA6ykRpoCZFe1qA8tSXrCpHHwH7BuWHDrVIohojOFvDNGRdwIfUu4Md7SjlqK+vwjqg5O4WngS6hwUvIhg2XXcwdF5/e6xnD8LcVkVrRF+/1,iv:J9xDPZAi980sPhZb3qhK3WIG7a/wUZA6mNNsbp6oets=,tag:MsGLcOC+j9Z/FMYKqQHeig==,type:str]
    secretsDefault: ENC[AES256_GCM,data:eBk6T5yn4JShSSRZxuKRUWgAF7St6yuF+3zaI67lWCVpXnkHEykU8AKsthKwIpvm0FqdIk9lSo9T3I52AxOaP0mHqsKv4icUhrODEyfuAcqgO2lAv61HnYEU4Bh2fE8ul9tUyoFKxDVFb5OYT7QjZwwGnr0UetgIvq7e3mv88HY=,iv:s+WTOCp/oJLKIl5RwY/NuBVvfb/b2V60KhSUabIqYLU=,tag:FWGO3SybpUujBvaFUy+5jw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyAwVHRx
            eEFabEdsRXl5ODI0WWFrM0tQczl3S0hCcU8xbnJrUk1YcTdUTmdZCm1aNHV5MzBj
            bVFSWkNXWkFtWjY3MUNhSGJRYmdpLzFDK2Y4QVlVbFBVemsKLS0tIDBRejlkYVJK
            cS83SnpZcFA3ZWYwd2dKczNueEcydjA3Yk4rSGlMeE9mSlkKXLorzxI2tlbgi0+Z
            9uRJgwstxerrZCVyFcx/rxFrWM9QB8DoK2v1EkqRnVn3NMunPK0z4zsaD24fmNGr
            mnxqSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T21:39:57Z"
    mac: ENC[AES256_GCM,data:Kb3WcSCc/HCDCNcdrOFt8VjptDDq4qNYd+3+0wd03iYaNmlbuvgExfmQ1ETkRzTPN5i9SxHexn49th2DZ0xBFBrqFBQX+Xaxq2QXnU9yVE13B+EzVpbHBdKOYxuky3/U2amp+f1M6iRWpzhe7aCeFoTRnZHtJpGDvWKbY9ntwRI=,iv:3hTdIzTvW8cv38V0xEP1cDi9BXRDpyPOfIp27I5u0jQ=,tag:aOlifLnj+PiAnHAMZS2rnQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
