---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 1
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: false
  managed:
    roles:
      - name: authentik
        passwordSecret:
          name: authentik-db-app
          key: password
