---
apiVersion: postgresql.cnpg.io/v1
kind: Role
metadata:
  name: authentik
  namespace: authentik
spec:
  name: authentik
  cluster:
    name: authentik-db
  passwordSecret:
    name: authentik-db-app
    key: password
