apiVersion: v1
kind: Secret
metadata:
    name: atuin-database-credentials
    namespace: atuin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hmR4KeU=,iv:inCWNAVLpqWYjR3VDTsQWjkZrphsprFqe7gnzGjRAu4=,tag:4iELtnetG1ay+yCdtBbdRQ==,type:str]
    password: ENC[AES256_GCM,data:QhmirBLb0cX+JZKIR3e/uTK1ed3DD8Nf/uA+X//kn3/m4XD6ZldJeVtV6s9mg8an,iv:bIvGYHXo7cqD7jQzGylvqrk6UdkaBrOq02qX6n0aLO0=,tag:Kjmk6jaI1yxT6jVHrgRC2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSTdrT3FhTXlEZHJzMVor
            U0JnNVd4RHI2NEJCSlM5anlldFJ1eEZwOHlVCmc2SVlsdlZnS2hyeDZESFNtaWVR
            V1BRUFAxeEF2TEt4ZjBtd3ZWVlhWeG8KLS0tIFQ5SitsdXc5RkpIOCtpMjdHdGp4
            Zi83N1grNGM0RTdXSkIvcFBzYWJxeVkKpo+bguRRwEXye2lefZTIkVcQR8JotnCv
            /BNxCihlx5lLUclhOQJP3r35+GMrJW/XSxVsjAq5DiFepX7/h5GwgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:18:23Z"
    mac: ENC[AES256_GCM,data:vTV3oCS6etJKDivpg4gw4WlkpLC7mCkmG5UlJCTPpzFa6Z/IVL87FknITj8oZ7iNC4PknAwxH9db62pzFKL2t3RiN/ynjlgt8nish2ZpFGV+F3VLS89wHgpOWpr1Qhtzh/dwOQ/vtDCoFPRSVxoHS+OV94mMol0vznhvRcBOl9M=,iv:MSiNPTODQNIJ3SzOBghV4D6cRj75wty8hGjaimj3eBQ=,tag:EJrf1FV60RhkmxIA3SXDzA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
