apiVersion: v1
kind: Secret
metadata:
    name: atuin-secrets
    namespace: atuin
type: Opaque
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:U1FaxXTlPzI68b0BIPdtAUpocfwkoG+9TWlkMx4a1/nTvS2Myh3NbQumoeANY6HDqN/Xhqu7seXgBcmodthU4lcohgseKhXWq+VHQn5SjmdTACN/mOMvukaV5gG6Ve3eZz4QrkhNX/PSJPgyzIdffkylzMlzuSG4,iv:0U2VlmgUc2N61b1XO+AqemMwvW2khFSlQGT26Y+ZwB8=,tag:7dUvZ0x6nlmxM2dnz9sRCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUWRRUVk1ZW1Cb05LWFlv
            TUJsQklXbmZsblRETlE1ekxQcCtpcmd4VEg0CmZrTTZrUi9QVkl2dmtyRFlDWGNZ
            MnBxL2gzRlA0bWxDNlQvRStHb3M4OUEKLS0tIFh2VTRyUE9jQVczYjhnQk5aeW1S
            MndTUE1KZEtqNm91M3htTWVtdXpnSkEKNi26MFdG6QVvWKz+78mgbil0+ogBkPVA
            cH8GfioPi7QUNWUTboPy57oNgjGHdL8w3N4Y/PM/S7k3ZxZEyF0SeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:18:23Z"
    mac: ENC[AES256_GCM,data:+BkMxh6gvskNaEZOa94zxxU9hrDa/TimYAcB3WQWDuw+Sd0+uSuRlDEFgWCB7GE/Cw0AiF98CzOHcviCKAt0XdjyDZx8axfz6bzBwk+eZ5lkWP5EdLg71swCkuwYBg3pIIv//sM8ja/AUI6qRo2jVjJ7gO2EDLJn+9c5DeeKY9A=,iv:l3Wu6Bx+jgBxoMCoFGOGnzb7aGJcmCX7PPOkO2k6p6A=,tag:2l2KMuoPxGI/S33iKDzOew==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
