apiVersion: v1
kind: Secret
metadata:
    name: kratos-selfservice-ui-node
    namespace: ory
stringData:
    secretsCookie: ENC[AES256_GCM,data:knl6KrkzKSOzBwtG3ZGLmpIjGiawffUa5EU1VYcPCEpTK+FJ1rNEo7PErltAOtU5GNxJIrrWrSzT3uHGqa+DSz0hn+WK0OQKjiXQmAsMrFJRBOHYEuhDu98lCTtC+UvGnWyTDKHj5m+3HZhTvvPVlEpd6ct1q3XZj7pgaAhtCAo=,iv:sj2s1grd9xS4QKKP3d5oU2bcUvJQxECAesNfzYeRH64=,tag:ydSfAokG8fOI6I2hdZBzQw==,type:str]
    secretsCSRFCookie: ENC[AES256_GCM,data:9qSBUYdPnbXhLAmvmHBPn8vbErX+8htLGXUEuDIoX78UJ8g8bYrTgJloZZTzaGKFLWd2g9DGJQ5apabS/rL7srlag8ntow4XIZ4P04QPyTQvcx5pRE7HhcUJfeRr/ZbEG9/8zYIEXjofQHrcS/BT8r6rbUChNsJtfUHkMnB4FiY=,iv:hNnY1OAlCVl3xamd1D1Wt59UBwbjzo2KC/1VJa5AJc4=,tag:bwjdUt7DFKCYLTy9u0Ol0A==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBuWmc2
            ZFdqQk11N2J4enVPSjV5YUtzNzBhRlRIWjBwa1ROQUd6WFFyTFc0ClVtTEg0QmE0
            QmI1ZFBYUTNQR1BNUmNLV01DMXhGOVZNZjJINEJtdE81Q0UKLS0tIHZkaGlWRVRv
            YlJDck5yOU9RMWxucmROL0ZRS244SCs1cnlSSlk0NDJiRjgKaPVo/XQQxznw1yrn
            oY0RwddYGMOaVo+W42deRHoxXVAtV02q1ytwB+JmDwGj28Fz6xEvq+DHpJEuZ76+
            Mdk7kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T11:34:38Z"
    mac: ENC[AES256_GCM,data:E//z30YZrtEpJ8WbsE4hot10g6V7PbUuCiyWIeZtS9LZ+Jjez/9cMyld/dSCzzfhHVhDLG4StkRb2SF17ttzY9Ab26ZEHuOqWy9szhcj3eIiKwIEzkRx1eybonHoqX6SHLYzhljb/LZjr4j+mG5L812dcB7RXzTaRobsCPZAG+o=,iv:GK0eu/wg4hsrVEUVASYT1WCzeMrmKBGu0pzf0vRzvNk=,tag:XdTfzSki7h/jye0HlmOu5Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
