---
kratosAdminUrl: http://kratos-admin.ory.svc.cluster.local
kratosPublicUrl: http://kratos-public.ory.svc.cluster.local
kratosBrowserUrl: https://identity.tomerhanochi.com

config:
  csrfCookieName: __Host-kratos-csrf

deployment:
  extraVolumes:
    - name: ca-bundle
      configMap:
        name: ca-bundle
  extraVolumeMounts:
    - name: ca-bundle
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: ca-certificates.crt
      readOnly: true

service:
  type: ClusterIP

secret:
  enabled: false
  nameOverride: kratos-selfservice-ui-node

ingress:
  enabled: false
