---
kratosAdminUrl: http://kratos-admin.ory.svc.cluster.local
kratosPublicUrl: http://kratos-public.ory.svc.cluster.local
kratosBrowserUrl: https://identity.tomerhanochi.com

config:
  csrfCookieName: __Host-kratos-csrf

deployment: {}

service:
  type: ClusterIP

secret:
  enabled: false
  nameOverride: kratos-selfservice-ui-node

ingress:
  enabled: false
