---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-allow-gateway
  namespace: paperless-ngx
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - ingress
