---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/tomerhanochi/homelab.git
