---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: qbittorrent-data
  resources:
    requests:
      storage: 1Ti
