apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn
    namespace: qbittorrent
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Xya37VOYUVPJZ6GhFk/+63yRg765DWvFhY5yBcnSyA2zVhaGpGIOnfPm,iv:XhaZDkBwGsv5h3Ch/BCoB1/zp6kNVBuue3TGlO+NGwc=,tag:sImipGPxE8STZyizPiqXIg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:5/Fgd6Bi0wvp8Mw=,iv:9/xuQzKgPkBRrhA+PLVLjybkfxIpyJbkU8u9GWfqy0I=,tag:40XXgwvJDqHmLdPao2rTqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMlJMVWZLM3c5ejd5OXRw
            N0JIbnZVM0lFZUk2WldXYUR0SCtRTTAwUmw0Ck5LVXhsSjlMSks5THNMYnE3aHhP
            VVN5STVaSHJMOVJBT045UTVFb1AxdkEKLS0tIEllSEJZRzlFaDJXbmErMEE3ZTZo
            RENBNGZkNGIwYm9EeGZab0tnZGZuRzgKD6+/I6MtwkAzMME7AGAUS+ylvP/N3d9g
            nR+dt1ACK9fOqkm9QD8BIqIQVeStfXgLQum5nWPRfVL4rDswlKqEGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:18:23Z"
    mac: ENC[AES256_GCM,data:mdFPwPPbNAZXVD78pTW206RPChOYDzLS3AZnscjQDRlXMTeK5B7+EWlTG7+XyRnI3Pbz3Zgw1/0HqexUyI+KaEqQ0GZazjsj8rROfQWty/umT6oUOPvV2SepRzGZo7egI0uQRy8LFkV0YslX8+6O0JaRMdMbAffK+bq25dNeXPc=,iv:sr2+flc/6vx8JaICavRNry6CT+QVMKhHRrgmpNhsx0k=,tag:Ao5EwAXCRJXGepP4Nqs6kQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
