apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn
    namespace: qbittorrent
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:j82rxb5v0vmF4mrKETpcIqjlCimNFM5Yy52tjIDDngA+unvSqdqyUkXXc7s=,iv:iq/zXN7L+pQK4NkWwiV0thKNk6XlLUUBo4nbiZR4FDo=,tag:5AT9tcx8nY6vcYa76dXb9g==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:5/Fgd6Bi0wvp8Mw=,iv:9/xuQzKgPkBRrhA+PLVLjybkfxIpyJbkU8u9GWfqy0I=,tag:40XXgwvJDqHmLdPao2rTqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMlJMVWZLM3c5ejd5OXRw
            N0JIbnZVM0lFZUk2WldXYUR0SCtRTTAwUmw0Ck5LVXhsSjlMSks5THNMYnE3aHhP
            VVN5STVaSHJMOVJBT045UTVFb1AxdkEKLS0tIEllSEJZRzlFaDJXbmErMEE3ZTZo
            RENBNGZkNGIwYm9EeGZab0tnZGZuRzgKD6+/I6MtwkAzMME7AGAUS+ylvP/N3d9g
            nR+dt1ACK9fOqkm9QD8BIqIQVeStfXgLQum5nWPRfVL4rDswlKqEGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-20T18:54:09Z"
    mac: ENC[AES256_GCM,data:IYeF7dmXqPddq7dl5ZafbW6XjA1UxEH4ErWkraDCRw2lBqVM403gQITQ39m2bQV7kik9WIY686CCCGS80NuOXN2wBFjJstoWodODH0xU8WWGsBy7D59hgR0bVa4O/8S6UeTtD4aG9LHFUjgNJ9gUkWCP/MPXBIjpRdWn8xvCoUs=,iv:LZNdW9JMVzVnT/xmE6QnSf3rQ9UE1HYcRFZScdtN9FI=,tag:E+r182NwA6rz0lTebG1Kxw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
