---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - selfsigned-issuer.yaml
  - ca-issuer.yaml
  - ca-certificate.yaml
  - ca-bundle.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: cert-manager
