---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicies
  - hydra
  - kratos
  - kratos-selfservice-ui-node

patches:
  - target:
      kind: CustomResourceDefinition
    path: patches/crd-argocd-sync-options.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ory
