graph TD
    User([User / Browser])

    subgraph Internet
        UI[kratos.tomerhanochi.com<br/>Selfservice UI]
        Hydra[sso.tomerhanochi.com<br/>Hydra Public API]
    end

    subgraph Cluster Internal
        KratosPublic[Kratos Public API<br/>:4433]
        KratosAdmin[Kratos Admin API<br/>:4434]
        HydraAdmin[Hydra Admin API<br/>:4445]
        HydraDB[(Hydra PostgreSQL)]
        KratosDB[(Kratos PostgreSQL)]
    end

    User -->|Login / Register / Settings| UI
    User -->|OAuth2 Authorization / Token| Hydra

    UI -->|Proxy browser requests| KratosPublic
    UI -->|Admin calls| KratosAdmin

    Hydra -->|Login / Consent redirect| UI
    Hydra -->|Validate sessions| KratosAdmin
    Hydra --> HydraDB
    HydraAdmin -->|Manage OAuth2 clients| HydraDB

    KratosPublic --> KratosDB

    HydraAdmin -.->|Used by internal services<br/>to create OAuth2 clients| Hydra
