---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateway-pool
spec:
  blocks:
    - cidr: 192.168.139.64/32
  serviceSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: default
