---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: media-sonarr-data
  resources:
    requests:
      storage: 1Ti
