apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oauth
    namespace: forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:+2gOYlSK7A==,iv:FsntcOF8aL27EgZpzsjo6ukaGAASOKA2RNFtWYxC5xY=,tag:IlSGsu2PjBeSagAJcuy+ew==,type:str]
    secret: ENC[AES256_GCM,data:Honf6V/HpHMxEekhgqI49mcOUQgbJ1ns0bm4N7MfEQujiDqmQt4rHZzKaGuGcJ8FXVbUHIPPILyZG7YmNtrPDw==,iv:kZdtxG8o+2WXL/r+3TNwp/CGuTLvb77F2aEAmw/WhjA=,tag:6Ft8aPVpZMPRopEK3FsA7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMjkzd0pSZFUyOWtIajZq
            SGVFUWRkbVFWb0xMSFdWLzhxZHFwTkt3QzFRCkQ2S1ZFZzNQSVdPaHRJbWlmWFhr
            WkNwd1RJdjF3aHVkT2Zsb1o2eE9UUEEKLS0tIGpnZHdyWFVsMGR6dWdxZHhCeFI3
            QnNLS3dFN3pUZDcrR3NSYm5ZTTFxVEkKtOruGwEFUoZjNGyxsXXMpNqhw/GPyErw
            03RiFMCT67syIk9p9MoUH3ZgNEJwhQK4kQyjpOXfqHg7Bn8I1HSBvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T20:42:27Z"
    mac: ENC[AES256_GCM,data:8swGMuo0VUb8VCtzCR97F51+YiY5898d9NGm/bx+8oyZ3LWojg9vRPbzpN4WCtRUJpBnnmeomwvt88KgJJV74AOcjccSqncWQAN08dnVHLzdRXusrqkkZbF4wOBXgjtO+Jyln+4dspoE8vNSGN9KT8F6Qu+sh5tA59xwiNmBq7Y=,iv:PZ8bp40QP6kLy4oSQfxmd7VJkwjhvRNntbSgq2e9gwc=,tag:2cqw6O75jBS5bdAmOaeD8g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
