apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oauth
    namespace: forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:XkRca0ieWNEN4+EihVmpBDyg5xg=,iv:+6oHTApY8eeung4qa2un0zBO4iTcg6oLRfH1JRvwiwA=,tag:pfczmSU8+aSOSLArbLkVRw==,type:str]
    secret: ENC[AES256_GCM,data:mfHyoXL3qQ5J78mKR30Ubhpq+xdMAchQ,iv:/40ss4L7x8JZOD3Gm+0/Q8gAtio1mIVLxlTGmEP0e9o=,tag:9PGP8Q0Cheoa2xgjo/w9bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z29XZVhBUDV6bTMwUURu
            dDBhajVBTkZoM29zWUo5bGtYelNFMU1Td0VZCjBzVmZkVlpiZHNFK0VZWjNQUy8w
            VHZqcE9UVUhvb0MxMmF4UzRXdVBXcWMKLS0tIGcyTGpuWFdhTUpkVk5KVjJXTWlq
            ZERKNWlWSjlQdGEwMytrNC9GaHdnVWMKGE3xcQ8JrTsj7raxYrabtSKq8BLlH8kR
            +VAh9HwQ4Im0fAlu7iw8vYBmIaoWXuIDNDiTjmuLdt7WOvFHKtsxOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:18:23Z"
    mac: ENC[AES256_GCM,data:z7dg8YxjdTRsVxvkViI5igSAk2vubNHaprECU5ECy7gcjvcKV6wnzClRoQiMHcMY3vh0zxUw1JJfdclNps2/27c8v87+0OJEC8kGffxEPpaZQxohutcBmoN8+62nojnvXFl1GSS+yXJDOaB8YjRGTLU08UXr04/EDocQCml+RmA=,iv:nPDH5er1jOEKteUJshgQbHEsxJT/qV8KjnnCOqvZkD8=,tag:TLGNaJug1NBW+DDoB5uNHA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
