apiVersion: v1
kind: Secret
metadata:
    name: forgejo-database-credentials
    namespace: forgejo
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Envrz2ahDg==,iv:nooWe4FlOIRIWpueslbGpKaifyjqluL/LiUcsoldxCE=,tag:gkk8vhek7pv5ZHVTVVXFNg==,type:str]
    password: ENC[AES256_GCM,data:CxEYfAVMtKF9q/1a6bAkK/aQT5SuAdQhiO9IAE1fSxC5EVWiTBQfyx+cJifKjuIo,iv:XzlF2QddG+B9CGdvPyo8BUtAWRI7bNTyZfsBUsM/uAQ=,tag:65DraSvEao0oZUABj+SHTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WFZIcTVqNS9qQXFHMXdX
            eHBzRkZreVBnYi9xVlh3bUlUYjYwcFRNTHlVCjA4Slpqajd0bm4yWXcxS0phSW5a
            dzBQeE9EZkRERXd3akdLSUlUczhqUUEKLS0tIGkvbFR1eDR0bDJzZ3Z0MUtOdkYx
            MFUvZ0dsY0kxUGVaeHVMci9ONVZ5dkkKU0GU1vqE6yy679lqbGopffpEjywGREq6
            +rqLhCiN+onYGzr6GY+QjoLs+2XRjK7BCG4x92IpAuC8pmgtKkZxKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:18:23Z"
    mac: ENC[AES256_GCM,data:BArRTMZ52k2NjEqyOUwO0pv1y8dgBQmmBjO6KnUVrib6Nc7yU5K1GAFdNxuBplRjfohohSmc5RELPlI5P5uqcd+Fm4tK77TGM4Z65jl9Ww3i+NMOl6le8U16z/ATcxLsq3f1q340nXyv8czegNR7KxMBJbqE1wi7ToF0hWV7Ma0=,iv:g/HGhlImm3LdFjVdxCkBecc/dRE8hPY6TnM3wz808fo=,tag:+N4Q1h43D+foLkTMVuyHXg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
