---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-database
  namespace: forgejo
spec:
  instances: 1
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-database-credentials
