apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-oidc-client-secret
    namespace: authentik
stringData:
    client_secret: ENC[AES256_GCM,data:sriGWn/dGICFaD5ye2VOzEqWDYN9a5kVD9IHuGeIaZQ8cpH3XLrW1sxiirnP948lKyJzqsf2KdWt1BjJYNlteoQhHS33Y0jrs0NaRkU8/Nr23DlzvPP0VUe+gJaftkQtr1VWdlBN2R3n1aOd8ul/1tJ2CpNQtjNFKh3njfUiqnc=,iv:D6VpK7PwMfoEw9fla41u0HhQntHOp+gL8QBe+RguL84=,tag:pBJw1tpODr8CKE6Bh7CowQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyAzY2lD
            ZkR0aTFUOC9wd2JTK1NHMU0rN2ZJdThod2hFd1pKSGhWcW80eFVNCkg1b3ZCS3Zp
            MFk5eWpnWlM5M1RPTTlMWHB6WFlvMGZTYmNZQ1lMK1JnTncKLS0tIHlzamhFdTUv
            WmtNMWtLSmhPNk5RS1VvYk1EMVE2VzNYdUJhMk1icmw3UlUKu9x6a2rK0mwOjX7R
            aFQahlcNTyeg2mwX2yAWdXqOkZatRiOlhPuc7oCRSH1GDvXWQ0EaKSHST124oAir
            hF6ICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:21:08Z"
    mac: ENC[AES256_GCM,data:ANfoGz/fH7TFe/kK5Yv/1FpkLJvAaz1p3h6zvQJTsGZE81/QXr0HN3UF8LS7J6LExjT87vUG4wDu0TvxB2kQKpv5eiGUe6l828jSke81L0h+RsdhFQ/Lh4B/9Bhipf9IC5+7keH4qGFM3gYSKKVm1vbGpgGYjvXkMBSozKWfxfg=,iv:+3QuLxJxJJC7tPqVVSnGTCsysFmNcLd/hgx4qvckX4A=,tag:XG7qD9h8N6ykfI68wad+jg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
