---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/flux-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
