---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-operator.yaml
  - trust-manager-operator.yaml
  - external-dns-operator.yaml
  - cloudnative-pg-operator.yaml
  - flux-operator.yaml
  - flux.yaml
  - cilium.yaml
  - cert-manager.yaml
  - gateway.yaml
  - authentik.yaml
  - forgejo.yaml
  - headlamp.yaml
  - media.yaml
  - kavita.yaml
  - qbittorrent.yaml
