---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-operator.yaml
  - trust-manager-operator.yaml
  - external-dns-operator.yaml
  - cloudnative-pg-operator.yaml
  - flux-operator.yaml
  - flux.yaml
  - cert-manager.yaml
  - gateway.yaml
  - authentik.yaml
  - forgejo.yaml
  - headlamp.yaml
  - homepage.yaml
  - jellyfin.yaml
  - seerr.yaml
  - kavita.yaml
  - paperless-ngx.yaml
  - qbittorrent.yaml
  - radarr.yaml
  - sonarr.yaml
