---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  path: ./apps/qbittorrent
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: gateway
  decryption:
    provider: sops
    secretRef:
      name: sops-age
