---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - persistentvolume.yaml
  - pvc-library.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - oidc-secret.sops.yaml
  - oidc-job.yaml
  - networkpolicies

labels:
  - pairs:
      app.kubernetes.io/part-of: kavita
