apiVersion: v1
kind: Secret
metadata:
    name: kavita-oidc
    namespace: kavita
type: Opaque
stringData:
    #ENC[AES256_GCM,data:k6UEll5378uqi1qQJz91CHGbsjcwgBqnI6jqz4OHxeSdynv0hktWon0r2nuH+FoYdc6ZmJjTU56VfDs3zYYdLOpQBqy5hgi5E+SnOiGRE/fZ7Q8=,iv:JNeL3ABG8H8ebCOgsaMov4Tl8f7WgWhjU88qySn5JH0=,tag:5C4TBySXh6l7qk7N0nlyew==,type:comment]
    #ENC[AES256_GCM,data:Jt1q9GihEhcDIAZcx1fkxvlKsbyVl3+jYPJ8wyp9UheY7xKAHI6i5PKEkNLinolwt9LmnHD6cfspU8G9781q5aqp4IQ6XZotQA==,iv:jzzlzuu5Eo46YGwYZbfdA54IBSQ0XOjIckWHArwWNKw=,tag:iyn8rPMCsNa9tJBolYEEOw==,type:comment]
    KAVITA_ADMIN_USER: ENC[AES256_GCM,data:N030D0Q=,iv:AW4kQ1IQzwoE9xsKLGDKWewFSNra5GrvvGA7LR/3u4A=,tag:2pWeJPXX3LWprM/5KsVcrg==,type:str]
    KAVITA_ADMIN_PASSWORD: ENC[AES256_GCM,data:eganqzLZ/bZNp/B1b6jNniXJIOCtlUmDbkhq1L3BfwrvNoVm6AYDDIJdeTFQpZ8y,iv:hI/PVde5eYbSiNOsO1ps9S/DkmNC+Fe5k/Eb8/0WOjI=,tag:cxC54lG3WBbNRKnn9ck3sA==,type:str]
    KAVITA_ADMIN_EMAIL: ENC[AES256_GCM,data:h5Q26rmmFGEn+mWJGmhteEJlQ6Uj5Q==,iv:U9wZyaj+WfIjR3r7GyXJ8WXxPXALvzdHdSNVCEFOPjc=,tag:4/posHIBh2CsH1ixynXNqQ==,type:str]
    #ENC[AES256_GCM,data:vFuvOHloVSLxxJVW8gFwG9ZnnOnUQXpvR6tg5xP0rHfiWuYGvjb0+Ts1O3+rhvdKwZMRGjlwjT2mVJeB1DfK3HYv3DpE8w==,iv:njcG6MJeG4DEFBTzb5hX6P7GEkED5r8Yh3+uOy5p1zI=,tag:tnyBmcAIUThZ6qIhj06X4Q==,type:comment]
    #ENC[AES256_GCM,data:d/kVbIPLIeX3KdfUSSMCD7jeDvmBQ7nh6cli14bSZhvdMGq6FANbYDKYvEZDjqU0j+L+4/VKep4aeo3bBF4=,iv:o9RTGN2t8uXrhQfprFEHKm23Q1X3Z7XDdNOutr5SCXY=,tag:/HyCUZ735T9z0f2u2gu9bA==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:BwgKY+KRC4+LFX6bz1DYOzitvPpW6rCRXL+XNMMdebdoK/1oVqGPHkp815sBoPKOo1RAkaxh3V42iAkzf8XALg==,iv:9asOgya3c9nhF9hnjiNFi2NMV7cVz9J/LKIakiiPZME=,tag:tilFFUIYVYWv94rmBxg81g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR1lvWENtSm9mc3g3NU1J
            b1BwcXNZc2lpOHBGeHpQNFFNUllEK3M4QmdVClhNY2hhMFBTWW1oZzZzTjFiemE5
            aHlvM1hFMzU4elpPS2JDUHZoRnhDZ3cKLS0tIDlOV1lMTXRCcnVIbXVYUDdUcXFa
            Z285bDl2LzYwaXJoTXFUMENPU3lVSUkKZv2fuTQuEMX/qH5V/mFOrrfbMBlLsIoF
            e9pcFsP4zVmU2UrptLo29ok9BtSC7fO/557cV4g1atThrYq0jnIZsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-20T08:00:32Z"
    mac: ENC[AES256_GCM,data:2pZT2Gx0rywE66/SSZqAOd9yiBOONHviSwUfrAtkZpyJgjCYnirjsuB/WlOSCl8NENLy5e0NDXGTBplNI2dzg9xLoJZx8Jvf76xHs7YhXsBEHjCsdtaHsXDYQlnGI4cEOOJPeTNirP48nKkoaQoLwpQJZb06NwSIxjfYEil7+Oc=,iv:J4McpSR98Dl1MJRhSbTNh0LFynIDbwCKKnyFpiWgHbg=,tag:D7JhYbimBd5HJtWGw342qw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
