FROM quay.io/bootc-devel/fedora-bootc-44-minimal:20260715-142243@sha256:17a7230c2e41360beef7c93fb1468acc5dff9aab23c9660d6020564c073c56f5

RUN \
  --mount=type=tmpfs,target=/var \
  --mount=type=bind,source=scripts/install-packages.sh,target=/install-packages.sh,relabel=private,ro=true \
  /install-packages.sh

RUN \
  --mount=type=tmpfs,target=/var \
  --mount=type=bind,source=scripts/install-k3s.sh,target=/install-k3s.sh,relabel=private,ro=true \
  /install-k3s.sh

COPY /usr /usr

RUN \
  --mount=type=bind,source=scripts/setup.sh,target=/setup.sh,relabel=private,ro=true \
  /setup.sh

RUN bootc container lint
