apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-database-credentials
    namespace: paperless-ngx
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/8jgW7PI5gaj,iv:iNehUTDQtrAsPHaGyG0CKQmGlV1FqBwuOkDe9gd90yc=,tag:6ZPzWwvMRQAC8BOImqai4Q==,type:str]
    password: ENC[AES256_GCM,data:7xG+3l3HEIudpR6++HNOi/YGyuw37joITqpc1AINQf1G/fEyvsc4PxWmzFZYlthe,iv:utiFlqsTdXSeaHhVdni2b2JCTQgBJOLCJqhIg0xA1pk=,tag:10n1T4mb9VFb9C2K1kWpWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvczFxb1lWSHJYclZaS0Fr
            ZzNTWXg2V1h0YkNsQ3U4ZU8zVjI2THY3MFhnCmVyMVE5L0JxbjZxTHJ5L2hLcnJX
            R0VKZmk3Rkk4NjQ5RzgzOUJFVVRDcUkKLS0tIDVkRVlNcXR4SnA5KzJwU0wyYUpa
            VmhqRGV1Sm1zU2lHQm5uamMycUkyUFUK9SK5WJVpJW1xgWn0hM8tw1GfL3kKKfuF
            TGIhxNUxk3N9JymJJ+83PPKCI9AyfOYCDIBtEsKo7bcXbqHW2GJMqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:18:23Z"
    mac: ENC[AES256_GCM,data:CeINJTZHep8lObOhUwLuMHvepRFzG7sYeJJJ+UxLkMnX8AV+2pps2ozGszqEGyoLv9VbBtgWylpA1St4fNw4vv8B4XWZ/7u9jd/hbxq8HtqHg0IZzR6moJosGhKy79it655i4F72C/dH4fVM5KtznJpH2jmZMCRt4/ko5gftOgI=,iv:3+5wJg5gxdRvRyHAMu/+5Vy4JmE6xX5qOYSOU4zblws=,tag:N4pP5BzlEgEfDGNhL5u5AQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
