apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secrets
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:jhrA+KgR4NNjmPhiYrllyWLcadslFfmGet5JNtdaljkamaQD0iO2TEfNfYk3QQ7ua1udTm7JCeebeSU7ohi/Rw==,iv:78OorM2Q7Bxo2Le9EiZyg3v+eJu0hJD7j1WkZCBVKCY=,tag:RaeI24p+cto3Jul1SmFiOA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:QvR55ZsiMQhQZaIETDWYX1ZsPTVaFG4VmgANe2KSLwkhUeHjeBoj8M16GCBRVuXw,iv:jeKpBY2CufDfOfQWAcy4s9JyhVGvQQo4Wl3evnxfiR4=,tag:Y2mA1GGSQgid2yr2oaTjBA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:sMsI4i33HwiMrHZf+q/1m1uhZEMQWcxmN8wpsCo6UOaIADjpyCq4/SrZV3DrkQQZyf+ZFKoHuBBBhRvyf7219k8qYzpI0NJG4bHeG78AAHsz8XO+/tyCqY9LRkSAABttRuYarU/gNZvKmCUcgQ+kU60F1wHdfmsZxrm9Bq/k0KRnNmwnCqsdDv2mHQZIooD5ORgaEg4LzdQfqW55lPo5f7xGlnE9GvfgF8IkHHYt4AytySZI06Qwz2v1Vzf112yumuRR8TznMpAisYnoD9ra16BA5QTb/s1wj49iyFlFLhDqUsLt4ppEhPBMEeq6QSMW/6UACZU6740t4i8y+EibTcEss53ZUkTbJv9aLAWVbnjHK/CR5jFjGd41bvC9xUjPAso=,iv:Ad19HLIii0N2+jQWhyDJnZgcyBTdBbnhfwzuLPiW28Y=,tag:hM7F95v+ho/rx+Utj8uirw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc0R3V2s4WE81aEVGUks5
            ZmRjMW8vR3FiMGRPTTY1OE9oMk1pazhGOGhVCjRnVURTcE1NRXlYeDVxaE5SRmZQ
            a1FzQWl3cGgyMDJEeEJKTWVGaUo3TmMKLS0tIGR2WW9HdEU5N0xocHVqYnNPL1VE
            c2E4Q2FhOGtWYTVrbTk1SWJkbmUwVm8KjXNdk8utOaMLSMkKPg9LLbQS5p+ppj/N
            HtzI7Vd7noRbXIIeiB+NXvUjhtHEvd6VRvzJc+DQ9W1mgtG2Gs9oWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T20:42:47Z"
    mac: ENC[AES256_GCM,data:PZS7S4loVH60Khwj/PYmurVVPO0B48orhHwZZyLJ1qm5IopC5AanjT0bP5Z+Yx5ix4yuIJkXyvkPB9nyD4mlz0KkCnSjtWZceJ2LahC/O29Yw9f/7RnqdVcDhIrfD1TyaU+9YLRAx+Nc3byXin61eIa/zbqPRf+EYWYlFv2NEr4=,iv:gx1zzZ+epzXe6Ky1HeRxnPsaMH4/Jh5jmwEGmMChE8U=,tag:KY8KMlXhz+AqzdZlN6DwDw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
