apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secrets
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:jhrA+KgR4NNjmPhiYrllyWLcadslFfmGet5JNtdaljkamaQD0iO2TEfNfYk3QQ7ua1udTm7JCeebeSU7ohi/Rw==,iv:78OorM2Q7Bxo2Le9EiZyg3v+eJu0hJD7j1WkZCBVKCY=,tag:RaeI24p+cto3Jul1SmFiOA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:QvR55ZsiMQhQZaIETDWYX1ZsPTVaFG4VmgANe2KSLwkhUeHjeBoj8M16GCBRVuXw,iv:jeKpBY2CufDfOfQWAcy4s9JyhVGvQQo4Wl3evnxfiR4=,tag:Y2mA1GGSQgid2yr2oaTjBA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:WDR8cxBiNYy0+pn88ix+XhuzMvZl5J2JCbsxPUw2JDbcsooS5enJCIdt7UMXm/D8UArIMsYj2mOXVHbxnvgIt8kCZpf+1nGo0rhOIOBxe+6cHMilKtt06IgH5RlXujVgetHgy+KcQs0zh7ugQdRNS/fTRjGye/cWebpMCy62xZuqJ7ZKVTvmDlMP1AAYPXDKhbgu5xlRkNPM7GcbtBULYqRQuDS4tU6383aCvUcUxtEL6Oa3qTBFT5zyqmDoHKgJtHRD4ysun3NcnILRuamYCnXGOOvCVOVRfq1tn0xY9aFWvw1k8P/u8HZc2wc=,iv:vfdKoapX2kWE9ZJwYUehIN+ATnPpFm2ieDTVhAEPb+E=,tag:8M4jh8Bh2AFA3yecdssjCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc0R3V2s4WE81aEVGUks5
            ZmRjMW8vR3FiMGRPTTY1OE9oMk1pazhGOGhVCjRnVURTcE1NRXlYeDVxaE5SRmZQ
            a1FzQWl3cGgyMDJEeEJKTWVGaUo3TmMKLS0tIGR2WW9HdEU5N0xocHVqYnNPL1VE
            c2E4Q2FhOGtWYTVrbTk1SWJkbmUwVm8KjXNdk8utOaMLSMkKPg9LLbQS5p+ppj/N
            HtzI7Vd7noRbXIIeiB+NXvUjhtHEvd6VRvzJc+DQ9W1mgtG2Gs9oWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jjpauwwlhgtvk8k75cdulk3eweu3et8v3fn4clr8gm7sergvj3vsachhh4
    lastmodified: "2026-07-19T19:59:00Z"
    mac: ENC[AES256_GCM,data:EIT0e9DxvtcyUBRjS5JaV6PukvTCETUwOfdb108F008PjemgCXgb65Z2IpsmKzTysoJRr4U/4QuQiRq1bJWY4TrVySGSDS4Xg9Yp0LpbSt6poiGP55YP1v0GOUUdfYMl9ftNJEa6bIAyd7oCgX6QmpVc/DZrHYgQJ70u7vsVrMk=,iv:8KHP/VfAsE5nmNXAQmQWltHZyWqkJHeixG/ASmqq8hs=,tag:xrO3umIwdpIF9moNrmP9gQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
