FROM quay.io/fedora-testing/fedora-bootc:42-minimal

COPY /usr /usr

RUN \
  --mount=type=tmpfs,target=/var \
  --mount=type=bind,source=setup.sh,target=/setup.sh,relabel=private,ro=true \
  /setup.sh

RUN bootc container lint
