apiVersion: v1
kind: Secret
metadata:
    name: argocd-client-secret
    namespace: argocd
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:Fue4Ke6l,iv:rRTzwratqCKI60nd4jJhZkOdw8fOBvwY5TbQ1x0fVsg=,tag:jE/2xCgP/18d2j5ost9Zjw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:9/ePqUvJQL9TCK4g5n/A5BDaYPGCTQ1p9Rx2gTnOmYGyhXtMUZZdDd2wwy2YcX730Vr7r+z0GNfXblu+zxx9QfN9mW2TLBAVxtv77TjwTY239pffpOD78oB0rZeigKpODwTeStZ9HYBi7uiqj6ypSObiqQL3yrY3MuO55A4w/tA=,iv:DUkagrscGTr3eK/k+dvQoikAMQmYxGRw9AQaLIHtERA=,tag:0Tqagu0YQ9IQ0FGsTa9Ufw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBMakFx
            VVl5UWNqUHVERW05K3lDZTZkcDFOVnNjS3FZd2tHc0UvajNkQVFRClYzb1RidWQ1
            bEdBaVc5VEFwSUZ4K1Y1RFhEMVc4WG1SNWhsTXpkVkt0Z0EKLS0tIHg2dG1JaVlt
            SExPQit6NmZ2MUtjZzcvQVFDcVVOa2ZqQUhxckZydmJWSFkKrVl/MAPG6YeTHala
            0Q8/m09ru18J5W8B2eagRkWj+CeFWe/mEgPNZeRhmZrLEkhcuv8pbxrY4bhrnE70
            k/be5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T21:38:24Z"
    mac: ENC[AES256_GCM,data:czcb+KBBPNO8oXgWIjI0iQ685r24sMOdiDQTZ6dpB7cwFpU5xFtjDOs56P2ZSViwUPq1yqhE9Dye4xvhDfscRMsHybMZO6hbFch+gN335qRrkG8G7b18gH6N20gXMKPBZk2M1GyUAgRv8S4Un2hVzszmi2jD+T/rG2mtVuELkE4=,iv:F+T4lTUvE+4tL+LsPv1hPR7+fkIwRvRb+PyY806r3V4=,tag:GBlNOtOI9bd3NiKdSITvsw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
