apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
stringData:
    oidc.sso.clientSecret: ENC[AES256_GCM,data:xdnVGZfNwBKli2TG+AX33GF+xPqnYVP5pceXGuA3aDGubV8/NU8GVqDI0XehsMG796kSuPABr9ZeJfpTQpXQqUgSHeBvdce/LluyFMeW/Qwpaa6aSVb2hP6rQE0sGrp717uRSDmTA92qYpwMJ3pJlJz6GhdTBTsOfQMbYLegaFE=,iv:8SoeiTe5JrhISUAIhSxftlHdVhYsVJVvSovFvVI63Ks=,tag:Ycl9VchdXf4KbXqK0dpJ7w==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyB1ek1U
            aHR1T2c4RDFncEVnSFBVYUNVU2x3czhWdFRxdWRkQTJkaCtucFNrCkU0Vmd4Smd4
            NnFsZDRzQ1U2NUdaODhIdWszMW5CTEV1NnppNm9kdlVFamsKLS0tIG43L2x1Z1d5
            MDBNazY5ODJ4eExFYUVtNzVrRENlTm1rUFMyWDhUSC9POFUKayzGPwFGGhHiNdnJ
            wu5hJYBA9oFeTmNgKbFAhpXVr9NUi92Dxc2EYq30krTDS/4KglzXdnjpOrQ7mW9K
            Dtn1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:22:03Z"
    mac: ENC[AES256_GCM,data:CRXQkbUcbZE8b2RZOlXpoXRfBStWpT6UUBNSia+alWkREOCfYnCWA+j8t86wGrp4Zp7M1rSQ9dDu+YnlievtwSeeXyPPaz2kS4KBdq3CoGOczEZo9Gx/jXk6nPuyoveCpNINavrPPTOrARZvZD3Q6Nmzt0dBCF7PtPh9uIz//8M=,iv:gOb9z1q+V1iKU7vy7aLcTcpNCxRSMIrnq25+1IQb/O4=,tag:sl9tEuOZNP3M+ZyXn+gRJg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
