---
# WARNING: Do not commit plaintext secrets to Git.
# Consider using SOPS (mozilla/sops) or Bitnami SealedSecrets for production.
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
stringData:
  admin.password: "$2b$12$SAkv5AflHlezmQub1NY5De4n9NapWkXF.BDamv1Z9xmZUbsK7y90W"
  admin.passwordMtime: "2025-08-25T16:00:00Z"
  oidc.sso.clientSecret: "XXX"  # TODO
