apiVersion: v1
kind: Secret
metadata:
    name: argocd-sops-ssh-private-key
    namespace: argocd
stringData:
    public_key: ENC[AES256_GCM,data:d3JJRC33DcTEsg6JCqxBsFQrEoruDWt8ly9lUOscLPp0rKxAX+LtC0KvRdF/Xj3LR4HuPBP4mjbUb1s228Ds+USPkKfd3ubvPzBs+eynFkxv,iv:V3OP3isfzTC1rdtSKjOjM/hq4oXE2i65ck5Ea/fp2uw=,tag:ZAivG5Yp4KdIrgWEVw7+jQ==,type:str]
    private_key: ENC[AES256_GCM,data:xd+bJOvZmlMO6JQ1mYbvVRJuOArObgvDI9QMlyN1nMOEgM0Blxni2STu/fTOolT0tjFjR5RUAK6bj9QcAW+io8bJSPMhPoEN8ad5dpJZo5V8Q86UNU7x7FvCa2BS7JxmRDzN5xrE/w01l7UI4f4LOXbov3iEL2XsvxQLmxZ5MLlZgN8adwCvASIfXxS95Yr9o04bLPwY3+j78LKavkOCR9Lxq+2aBj2Q9TuQwojGTob0CZq3Au/krmsVKIV/Uzbm7OwUFvvatJq8S/BcVsJwhSaaTCJsfS6/FH1jdeOjkoefveZkg+K48oxkGMNR4Kb/aO0y5vt++Hgmvz/l2Fb3DPwXq+94fSZV2b/+ApI04f8NgyEp3FLW9sttEJa2m/ikXQWZZ/qITyBXcvJAFq92Cqhdd5jzPE04HsrFOvWfJd4AB4hyJ+gIoJQ/dygpEvYQGe14UJERLIkwpRH5OAR7GqeXjH/7y/9xk9DGMwWO8LGLUdEVgz7xdeXcklQ5iBJIsuM=,iv:gStqdzKT5S5041H4T+vWQ3rJ382z15n4htn5TljwlPY=,tag:JRX15jrrkK7PLTKM27aDRQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElU9nABetlwxlF7Nf9YS4fy15NV3ll1+07rsul8Mewq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGlGcHgyZyBrdDdN
            ZVd2L2NBeEdudUd2UHViTXNnak9aMEdib3k0Y0hSZ0ZxVU05RVhjCllTT1Y0L2li
            YU14M1Nad0xmUUkrMWFNTHM1UHNPT0o5ME1CTXR5WnlWbE0KLS0tIHRVdUVrV2dz
            aCtMeHZmODdNRDg4UXlUYU8xQ0xGRHU1V3ZhNTQ0U3BtT00KyS+dInBTF77Jn9iT
            FVKbkK0A3fATxZhXnDhtnsirQcL8+JmV+2PR/P3C4ZLZcVezwOjuF9NxOkEdBhIk
            nZrpNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:20:36Z"
    mac: ENC[AES256_GCM,data:BryfnSNPyR0S1xbdSzV28itLVngfNnLomUbO99SzPP9zZ8iD/vPz0EOonjq+JkfMP5zZwexBukgAI2o9pTy9z9XqEjlByGij8Nmano/CAQMze/WQp8DS9d60lQ7ZTYE51z5BmDRaznnT1ml1b5le5aYmfktauKZ3bVFsqBNdI30=,iv:3iU+RZumpxzCYmNcIc4C4shtgM13PTwjaZRc2FgFjo0=,tag:x2EkOEX3lU7sPs4x3tOZpw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
