---
namespaceOverride: argocd

crds:
  install: true

createAggregateRoles: true
createClusterRoles: true

global:
  logging:
    format: json
    level: info

  networkPolicy:
    create: true
    defaultDenyIngress: true

server:
  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: tailscale-ingress-proxy-group
      tailscale.com/funnel: "true"
    hosts:
      - host: argocd

configs:
  cm:
    url: https://argocd.glb.svc.tomerhanochi.com
    application.resourceTrackingMethod: annotation
    kustomize.buildOptions: >-
      --enable-helm
      --enable-alpha-plugins
      --enable-exec
      --network
    oidc.config: |-
      name: sso
      issuer: https://sso.glb.svc.tomerhanochi.com
      clientID: argocd
      clientSecret: $oidc.sso.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

  params:
    server.insecure: true

  secret:
    createSecret: false

repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.4.1
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Installing KSOPS..."
          cp /usr/local/bin/ksops /custom-tools/
          cp /usr/local/bin/kustomize /custom-tools/
          echo "Done."
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

dex:
  enabled: false

notifications:
  enabled: false
