---
namespaceOverride: argocd

crds:
  install: true

createAggregateRoles: true
createClusterRoles: true

global:
  logging:
    format: json
    level: info

  networkPolicy:
    create: true
    defaultDenyIngress: true

server:
  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: tailscale-ingress-proxy-group
      tailscale.com/funnel: "true"
    hosts:
      - host: argocd

configs:
  cm:
    admin.enabled: "true"
    url: https://argocd.glb.svc.tomerhanochi.com
    application.resourceTrackingMethod: annotation
    kustomize.buildOptions: >-
      --enable-helm
      --enable-alpha-plugins
      --enable-exec
      --network
    oidc.config: |-
      name: sso
      issuer: https://sso.glb.svc.tomerhanochi.com
      clientID: argocd
      clientSecret: $oidc.sso.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

  params:
    server.insecure: true

  secret:
    createSecret: false

repoServer:
  env:
    - name: SOPS_AGE_SSH_PRIVATE_KEY_FILE
      value: /run/secrets/sops/ssh/private_key
    - name: PATH
      value: /ksops/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  volumes:
    - name: sops-ssh-private-key
      secret:
        secretName: argocd-sops-ssh-private-key
    - name: ksops
      image:
        reference: viaductoss/ksops:v4.4.0
        pullPolicy: IfNotPresent
  volumeMounts:
    - mountPath: /ksops
      name: ksops
      readOnly: true
    - name: sops-ssh-private-key
      mountPath: /run/secrets/sops/ssh
      readOnly: true

dex:
  enabled: false

notifications:
  enabled: false
