---
namespaceOverride: argocd

crds:
  install: true

createAggregateRoles: true
createClusterRoles: true

global:
  logging:
    format: json
    level: info

  networkPolicy:
    create: true
    defaultDenyIngress: true

server:
  ingress:
    enabled: false

configs:
  cm:
    admin.enabled: "true"
    url: https://argocd.tomerhanochi.com
    application.resourceTrackingMethod: annotation
    kustomize.buildOptions: >-
      --enable-helm
      --enable-alpha-plugins
      --enable-exec
      --network
    oidc.config: |-
      name: SSO
      issuer: https://auth.tomerhanochi.com
      clientID: argocd
      clientSecret: $oidc.sso.clientSecret
      requestedScopes:
        - openid
        - offline_access
      rootCA: ""
      tlsInsecureSkipVerify: true

  params:
    server.insecure: true

  secret:
    createSecret: false

repoServer:
  env:
    - name: SOPS_AGE_SSH_PRIVATE_KEY_FILE
      value: /run/secrets/sops/ssh/private_key
    - name: PATH
      value: /ksops/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  volumes:
    - name: sops-ssh-private-key
      secret:
        secretName: argocd-sops-ssh-private-key
    - name: ksops
      image:
        reference: viaductoss/ksops:v4.4.0
        pullPolicy: IfNotPresent
  volumeMounts:
    - mountPath: /ksops
      name: ksops
      readOnly: true
    - name: sops-ssh-private-key
      mountPath: /run/secrets/sops/ssh
      readOnly: true

dex:
  enabled: false

notifications:
  enabled: false
